# Install pip requirements.
#
# Generated from /Users/lauri/go/src/github.com/bazelbuild/rules_python/examples/checked_in_requirements_bzl/requirements.txt
# Generated from /Users/lauri/go/src/github.com/bazelbuild/rules_python/examples/checked_in_requirements_bzl/requirements-2.txt
wheels = {
    "atomicwrites": {
        "name": "examples_checked_in_requirements_bzl__atomicwrites_1_2_1",
        "version": "1.2.1",
        "wheel_name": "atomicwrites-1.2.1-py2.py3-none-any.whl",
    },
    "attrs": {
        "name": "examples_checked_in_requirements_bzl__attrs_18_2_0",
        "version": "18.2.0",
        "wheel_name": "attrs-18.2.0-py2.py3-none-any.whl",
    },
    "backports.functools-lru-cache": {
        "name": "examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5",
        "version": "1.5",
        "wheel_name": "backports.functools_lru_cache-1.5-py2.py3-none-any.whl",
    },
    "backports.ssl-match-hostname": {
        "name": "examples_checked_in_requirements_bzl__backports_ssl_match_hostname_3_5_0_1",
        "version": "3.5.0.1",
        "wheel_name": "backports.ssl_match_hostname-3.5.0.1-py2-none-any.whl",
    },
    "botocore": {
        "name": "examples_checked_in_requirements_bzl__botocore_1_12_80",
        "version": "1.12.80",
        "wheel_name": "botocore-1.12.80-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["docutils", "jmespath", "python-dateutil", "six", "urllib3"],
    },
    "cachetools": {
        "name": "examples_checked_in_requirements_bzl__cachetools_3_0_0",
        "version": "3.0.0",
        "wheel_name": "cachetools-3.0.0-py2.py3-none-any.whl",
    },
    "certifi": {
        "name": "examples_checked_in_requirements_bzl__certifi_2018_11_29",
        "version": "2018.11.29",
        "wheel_name": "certifi-2018.11.29-py2.py3-none-any.whl",
    },
    "chardet": {
        "name": "examples_checked_in_requirements_bzl__chardet_3_0_4",
        "version": "3.0.4",
        "wheel_name": "chardet-3.0.4-py2.py3-none-any.whl",
    },
    "dill": {
        "name": "examples_checked_in_requirements_bzl__dill_0_2_8_2",
        "version": "0.2.8.2",
        "wheel_name": "dill-0.2.8.2-py2-none-any.whl",
    },
    "docutils": {
        "name": "examples_checked_in_requirements_bzl__docutils_0_14",
        "version": "0.14",
        "wheel_name": "docutils-0.14-py2-none-any.whl",
    },
    "enum34": {
        "name": "examples_checked_in_requirements_bzl__enum34_1_1_6",
        "version": "1.1.6",
        "wheel_name": "enum34-1.1.6-py2-none-any.whl",
    },
    "funcsigs": {
        "name": "examples_checked_in_requirements_bzl__funcsigs_1_0_2",
        "version": "1.0.2",
        "wheel_name": "funcsigs-1.0.2-py2.py3-none-any.whl",
    },
    "future": {
        "name": "examples_checked_in_requirements_bzl__future_0_16_0",
        "version": "0.16.0",
        "wheel_name": "future-0.16.0-py2-none-any.whl",
    },
    "futures": {
        "name": "examples_checked_in_requirements_bzl__futures_3_2_0",
        "version": "3.2.0",
        "wheel_name": "futures-3.2.0-py2-none-any.whl",
    },
    "gapic-google-cloud-datastore-v1": {
        "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_datastore_v1_0_15_3",
        "version": "0.15.3",
        "wheel_name": "gapic_google_cloud_datastore_v1-0.15.3-py2-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "gapic-google-cloud-error-reporting-v1beta1": {
        "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_error_reporting_v1beta1_0_15_3",
        "version": "0.15.3",
        "wheel_name": "gapic_google_cloud_error_reporting_v1beta1-0.15.3-py2-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-error-reporting-v1beta1", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "gapic-google-cloud-logging-v2": {
        "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_logging_v2_0_91_3",
        "version": "0.91.3",
        "wheel_name": "gapic_google_cloud_logging_v2-0.91.3-py2-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-api-core": {
        "name": "examples_checked_in_requirements_bzl__google_api_core_0_1_4",
        "version": "0.1.4",
        "wheel_name": "google_api_core-0.1.4-py2.py3-none-any.whl",
        "extras": ["grpc"],
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-auth", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-auth": {
        "name": "examples_checked_in_requirements_bzl__google_auth_1_6_2",
        "version": "1.6.2",
        "wheel_name": "google_auth-1.6.2-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "pyasn1", "pyasn1-modules", "rsa", "six"],
    },
    "google-cloud": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_0_29_0",
        "version": "0.29.0",
        "wheel_name": "google_cloud-0.29.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-datastore-v1", "gapic-google-cloud-error-reporting-v1beta1", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-bigquery", "google-cloud-bigtable", "google-cloud-core", "google-cloud-datastore", "google-cloud-dns", "google-cloud-error-reporting", "google-cloud-firestore", "google-cloud-language", "google-cloud-logging", "google-cloud-monitoring", "google-cloud-pubsub", "google-cloud-resource-manager", "google-cloud-runtimeconfig", "google-cloud-spanner", "google-cloud-speech", "google-cloud-storage", "google-cloud-trace", "google-cloud-translate", "google-cloud-videointelligence", "google-cloud-vision", "google-gax", "google-resumable-media", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "proto-google-cloud-error-reporting-v1beta1", "proto-google-cloud-logging-v2", "protobuf", "psutil", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-bigquery": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_bigquery_0_28_0",
        "version": "0.28.0",
        "wheel_name": "google_cloud_bigquery-0.28.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-resumable-media", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-bigtable": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_bigtable_0_28_1",
        "version": "0.28.1",
        "wheel_name": "google_cloud_bigtable-0.28.1-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-core": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_core_0_28_1",
        "version": "0.28.1",
        "wheel_name": "google_cloud_core-0.28.1-py2.py3-none-any.whl",
        "extras": ["grpc"],
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-datastore": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_datastore_1_4_0",
        "version": "1.4.0",
        "wheel_name": "google_cloud_datastore-1.4.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-datastore-v1", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-dns": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_dns_0_28_0",
        "version": "0.28.0",
        "wheel_name": "google_cloud_dns-0.28.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-error-reporting": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_error_reporting_0_28_0",
        "version": "0.28.0",
        "wheel_name": "google_cloud_error_reporting-0.28.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-error-reporting-v1beta1", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-core", "google-cloud-logging", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-error-reporting-v1beta1", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-firestore": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_firestore_0_28_0",
        "version": "0.28.0",
        "wheel_name": "google_cloud_firestore-0.28.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-language": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_language_0_31_0",
        "version": "0.31.0",
        "wheel_name": "google_cloud_language-0.31.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "enum34", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "grpcio", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-logging": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_logging_1_4_0",
        "version": "1.4.0",
        "wheel_name": "google_cloud_logging-1.4.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-monitoring": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_monitoring_0_28_1",
        "version": "0.28.1",
        "wheel_name": "google_cloud_monitoring-0.28.1-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-pubsub": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_pubsub_0_29_4",
        "version": "0.29.4",
        "wheel_name": "google_cloud_pubsub-0.29.4-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "enum34", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "idna", "protobuf", "psutil", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-resource-manager": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_resource_manager_0_28_3",
        "version": "0.28.3",
        "wheel_name": "google_cloud_resource_manager-0.28.3-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-runtimeconfig": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_runtimeconfig_0_28_3",
        "version": "0.28.3",
        "wheel_name": "google_cloud_runtimeconfig-0.28.3-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-spanner": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_spanner_0_29_0",
        "version": "0.29.0",
        "wheel_name": "google_cloud_spanner-0.29.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-speech": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_speech_0_30_0",
        "version": "0.30.0",
        "wheel_name": "google_cloud_speech-0.30.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-storage": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_storage_1_6_0",
        "version": "1.6.0",
        "wheel_name": "google_cloud_storage-1.6.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-resumable-media", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-trace": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_trace_0_16_0",
        "version": "0.16.0",
        "wheel_name": "google_cloud_trace-0.16.0-py2-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-translate": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_translate_1_3_3",
        "version": "1.3.3",
        "wheel_name": "google_cloud_translate-1.3.3-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-videointelligence": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_videointelligence_0_28_0",
        "version": "0.28.0",
        "wheel_name": "google_cloud_videointelligence-0.28.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-cloud-vision": {
        "name": "examples_checked_in_requirements_bzl__google_cloud_vision_0_28_0",
        "version": "0.28.0",
        "wheel_name": "google_cloud_vision-0.28.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-gax": {
        "name": "examples_checked_in_requirements_bzl__google_gax_0_15_16",
        "version": "0.15.16",
        "wheel_name": "google_gax-0.15.16-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
    },
    "google-resumable-media": {
        "name": "examples_checked_in_requirements_bzl__google_resumable_media_0_3_2",
        "version": "0.3.2",
        "wheel_name": "google_resumable_media-0.3.2-py2.py3-none-any.whl",
        "extras": ["requests"],
        "transitive_runtime_deps": ["six"],
    },
    "googleapis-common-protos": {
        "name": "examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_6",
        "version": "1.5.6",
        "wheel_name": "googleapis_common_protos-1.5.6-py2-none-any.whl",
        "extras": ["grpc"],
        "transitive_runtime_deps": ["protobuf", "setuptools", "six"],
    },
    "grpc-google-iam-v1": {
        "name": "examples_checked_in_requirements_bzl__grpc_google_iam_v1_0_11_4",
        "version": "0.11.4",
        "wheel_name": "grpc_google_iam_v1-0.11.4-py2-none-any.whl",
        "transitive_runtime_deps": ["enum34", "futures", "googleapis-common-protos", "grpcio", "protobuf", "setuptools", "six"],
    },
    "grpcio": {
        "name": "examples_checked_in_requirements_bzl__grpcio_1_18_0",
        "version": "1.18.0",
        "wheel_name": "grpcio-1.18.0-cp27-cp27m-macosx_10_9_x86_64.whl",
        "transitive_runtime_deps": ["enum34", "futures", "six"],
    },
    "h5py": {
        "name": "examples_checked_in_requirements_bzl__h5py_2_9_0",
        "version": "2.9.0",
        "wheel_name": "h5py-2.9.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl",
        "transitive_runtime_deps": ["numpy", "six"],
    },
    "httplib2": {
        "name": "examples_checked_in_requirements_bzl__httplib2_0_12_0",
        "version": "0.12.0",
        "wheel_name": "httplib2-0.12.0-py2-none-any.whl",
    },
    "idna": {
        "name": "examples_checked_in_requirements_bzl__idna_2_8",
        "version": "2.8",
        "wheel_name": "idna-2.8-py2.py3-none-any.whl",
    },
    "jmespath": {
        "name": "examples_checked_in_requirements_bzl__jmespath_0_9_3",
        "version": "0.9.3",
        "wheel_name": "jmespath-0.9.3-py2.py3-none-any.whl",
    },
    "keras": {
        "name": "examples_checked_in_requirements_bzl__keras_2_2_2",
        "version": "2.2.2",
        "wheel_name": "Keras-2.2.2-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
    },
    "keras-applications": {
        "name": "examples_checked_in_requirements_bzl__keras_applications_1_0_4",
        "version": "1.0.4",
        "wheel_name": "Keras_Applications-1.0.4-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
    },
    "keras-preprocessing": {
        "name": "examples_checked_in_requirements_bzl__keras_preprocessing_1_0_2",
        "version": "1.0.2",
        "wheel_name": "Keras_Preprocessing-1.0.2-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
    },
    "mock": {
        "name": "examples_checked_in_requirements_bzl__mock_2_0_0",
        "version": "2.0.0",
        "wheel_name": "mock-2.0.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["funcsigs", "pbr", "six"],
    },
    "more-itertools": {
        "name": "examples_checked_in_requirements_bzl__more_itertools_5_0_0",
        "version": "5.0.0",
        "wheel_name": "more_itertools-5.0.0-py2-none-any.whl",
        "transitive_runtime_deps": ["six"],
    },
    "numpy": {
        "name": "examples_checked_in_requirements_bzl__numpy_1_14_0",
        "version": "1.14.0",
        "wheel_name": "numpy-1.14.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl",
    },
    "oauth2client": {
        "name": "examples_checked_in_requirements_bzl__oauth2client_3_0_0",
        "version": "3.0.0",
        "wheel_name": "oauth2client-3.0.0-py2-none-any.whl",
        "transitive_runtime_deps": ["httplib2", "pyasn1", "pyasn1-modules", "rsa", "six"],
    },
    "pathlib2": {
        "name": "examples_checked_in_requirements_bzl__pathlib2_2_3_3",
        "version": "2.3.3",
        "wheel_name": "pathlib2-2.3.3-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["scandir", "six"],
    },
    "pbr": {
        "name": "examples_checked_in_requirements_bzl__pbr_5_1_1",
        "version": "5.1.1",
        "wheel_name": "pbr-5.1.1-py2.py3-none-any.whl",
    },
    "pip": {
        "name": "examples_checked_in_requirements_bzl__pip_9_0_0",
        "version": "9.0.0",
        "wheel_name": "pip-9.0.0-py2.py3-none-any.whl",
    },
    "pluggy": {
        "name": "examples_checked_in_requirements_bzl__pluggy_0_8_1",
        "version": "0.8.1",
        "wheel_name": "pluggy-0.8.1-py2.py3-none-any.whl",
    },
    "ply": {
        "name": "examples_checked_in_requirements_bzl__ply_3_8",
        "version": "3.8",
        "wheel_name": "ply-3.8-py2.py3-none-any.whl",
    },
    "proto-google-cloud-datastore-v1": {
        "name": "examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4",
        "version": "0.90.4",
        "wheel_name": "proto_google_cloud_datastore_v1-0.90.4-py2-none-any.whl",
        "extras": ["grpc"],
        "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
    },
    "proto-google-cloud-error-reporting-v1beta1": {
        "name": "examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3",
        "version": "0.15.3",
        "wheel_name": "proto_google_cloud_error_reporting_v1beta1-0.15.3-py2-none-any.whl",
        "extras": ["grpc"],
        "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
    },
    "proto-google-cloud-logging-v2": {
        "name": "examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3",
        "version": "0.91.3",
        "wheel_name": "proto_google_cloud_logging_v2-0.91.3-py2-none-any.whl",
        "extras": ["grpc"],
        "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
    },
    "protobuf": {
        "name": "examples_checked_in_requirements_bzl__protobuf_3_6_1",
        "version": "3.6.1",
        "wheel_name": "protobuf-3.6.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl",
        "transitive_runtime_deps": ["setuptools", "six"],
    },
    "psutil": {
        "name": "examples_checked_in_requirements_bzl__psutil_5_4_8",
        "version": "5.4.8",
        "wheel_name": "psutil-5.4.8-cp27-cp27m-macosx_10_14_x86_64.whl",
        "extras": ["enum"],
    },
    "py": {
        "name": "examples_checked_in_requirements_bzl__py_1_7_0",
        "version": "1.7.0",
        "wheel_name": "py-1.7.0-py2.py3-none-any.whl",
    },
    "pyasn1": {
        "name": "examples_checked_in_requirements_bzl__pyasn1_0_4_5",
        "version": "0.4.5",
        "wheel_name": "pyasn1-0.4.5-py2.py3-none-any.whl",
    },
    "pyasn1-modules": {
        "name": "examples_checked_in_requirements_bzl__pyasn1_modules_0_2_3",
        "version": "0.2.3",
        "wheel_name": "pyasn1_modules-0.2.3-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["pyasn1"],
    },
    "pytest": {
        "name": "examples_checked_in_requirements_bzl__pytest_4_1_1",
        "version": "4.1.1",
        "wheel_name": "pytest-4.1.1-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["atomicwrites", "attrs", "funcsigs", "more-itertools", "pathlib2", "pluggy", "py", "scandir", "setuptools", "six"],
    },
    "pytest-mock": {
        "name": "examples_checked_in_requirements_bzl__pytest_mock_1_6_2",
        "version": "1.6.2",
        "wheel_name": "pytest_mock-1.6.2-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["atomicwrites", "attrs", "funcsigs", "mock", "more-itertools", "pathlib2", "pbr", "pluggy", "py", "pytest", "scandir", "setuptools", "six"],
    },
    "python-dateutil": {
        "name": "examples_checked_in_requirements_bzl__python_dateutil_2_7_5",
        "version": "2.7.5",
        "wheel_name": "python_dateutil-2.7.5-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["six"],
    },
    "pytz": {
        "name": "examples_checked_in_requirements_bzl__pytz_2018_9",
        "version": "2018.9",
        "wheel_name": "pytz-2018.9-py2.py3-none-any.whl",
    },
    "pyyaml": {
        "name": "examples_checked_in_requirements_bzl__pyyaml_3_13",
        "version": "3.13",
        "wheel_name": "PyYAML-3.13-cp27-cp27m-macosx_10_14_x86_64.whl",
    },
    "requests": {
        "name": "examples_checked_in_requirements_bzl__requests_2_21_0",
        "version": "2.21.0",
        "wheel_name": "requests-2.21.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["certifi", "chardet", "idna", "urllib3"],
    },
    "rsa": {
        "name": "examples_checked_in_requirements_bzl__rsa_4_0",
        "version": "4.0",
        "wheel_name": "rsa-4.0-py2.py3-none-any.whl",
        "transitive_runtime_deps": ["pyasn1"],
    },
    "scandir": {
        "name": "examples_checked_in_requirements_bzl__scandir_1_9_0",
        "version": "1.9.0",
        "wheel_name": "scandir-1.9.0-cp27-cp27m-macosx_10_14_x86_64.whl",
    },
    "scikit-learn": {
        "name": "examples_checked_in_requirements_bzl__scikit_learn_0_17_1",
        "version": "0.17.1",
        "wheel_name": "scikit_learn-0.17.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl",
    },
    "scipy": {
        "name": "examples_checked_in_requirements_bzl__scipy_0_17_1",
        "version": "0.17.1",
        "wheel_name": "scipy-0.17.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl",
        "transitive_runtime_deps": ["numpy"],
    },
    "setuptools": {
        "name": "examples_checked_in_requirements_bzl__setuptools_40_6_3",
        "version": "40.6.3",
        "wheel_name": "setuptools-40.6.3-py2.py3-none-any.whl",
        "extras": ["certs", "ssl"],
    },
    "setuptools-scm": {
        "name": "examples_checked_in_requirements_bzl__setuptools_scm_2_0_0",
        "version": "2.0.0",
        "wheel_name": "setuptools_scm-2.0.0-py2.py3-none-any.whl",
    },
    "six": {
        "name": "examples_checked_in_requirements_bzl__six_1_12_0",
        "version": "1.12.0",
        "wheel_name": "six-1.12.0-py2.py3-none-any.whl",
    },
    "urllib3": {
        "name": "examples_checked_in_requirements_bzl__urllib3_1_24_1",
        "version": "1.24.1",
        "wheel_name": "urllib3-1.24.1-py2.py3-none-any.whl",
    },
}
