# Install pip requirements.
#
# Generated from /home/lpeltonen/go/src/github.com/bazelbuild/rules_python/examples/checked_in_requirements_bzl/requirements.txt
# Generated from /home/lpeltonen/go/src/github.com/bazelbuild/rules_python/examples/checked_in_requirements_bzl/requirements-2.txt

load("@examples_checked_in_requirements_bzl//python:whl.bzl", "whl_library")

_requirements = {
    "atomicwrites": "@examples_checked_in_requirements_bzl__atomicwrites_1_2_1//:pkg",
    "atomicwrites:dirty": "@examples_checked_in_requirements_bzl__atomicwrites_1_2_1_dirty//:pkg",
    "attrs": "@examples_checked_in_requirements_bzl__attrs_18_2_0//:pkg",
    "attrs:dirty": "@examples_checked_in_requirements_bzl__attrs_18_2_0_dirty//:pkg",
    "backports.functools-lru-cache": "@examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5//:pkg",
    "backports.functools-lru-cache:dirty": "@examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5_dirty//:pkg",
    "backports.ssl-match-hostname": "@examples_checked_in_requirements_bzl__backports_ssl_match_hostname_3_5_0_1//:pkg",
    "backports.ssl-match-hostname:dirty": "@examples_checked_in_requirements_bzl__backports_ssl_match_hostname_3_5_0_1_dirty//:pkg",
    "botocore": "@examples_checked_in_requirements_bzl__botocore_1_12_33//:pkg",
    "botocore:dirty": "@examples_checked_in_requirements_bzl__botocore_1_12_33_dirty//:pkg",
    "cachetools": "@examples_checked_in_requirements_bzl__cachetools_2_1_0//:pkg",
    "cachetools:dirty": "@examples_checked_in_requirements_bzl__cachetools_2_1_0_dirty//:pkg",
    "certifi": "@examples_checked_in_requirements_bzl__certifi_2018_10_15//:pkg",
    "certifi:dirty": "@examples_checked_in_requirements_bzl__certifi_2018_10_15_dirty//:pkg",
    "chardet": "@examples_checked_in_requirements_bzl__chardet_3_0_4//:pkg",
    "chardet:dirty": "@examples_checked_in_requirements_bzl__chardet_3_0_4_dirty//:pkg",
    "dill": "@examples_checked_in_requirements_bzl__dill_0_2_8_2//:pkg",
    "dill:dirty": "@examples_checked_in_requirements_bzl__dill_0_2_8_2_dirty//:pkg",
    "docutils": "@examples_checked_in_requirements_bzl__docutils_0_14//:pkg",
    "docutils:dirty": "@examples_checked_in_requirements_bzl__docutils_0_14_dirty//:pkg",
    "enum34": "@examples_checked_in_requirements_bzl__enum34_1_1_6//:pkg",
    "enum34:dirty": "@examples_checked_in_requirements_bzl__enum34_1_1_6_dirty//:pkg",
    "funcsigs": "@examples_checked_in_requirements_bzl__funcsigs_1_0_2//:pkg",
    "funcsigs:dirty": "@examples_checked_in_requirements_bzl__funcsigs_1_0_2_dirty//:pkg",
    "future": "@examples_checked_in_requirements_bzl__future_0_16_0//:pkg",
    "future:dirty": "@examples_checked_in_requirements_bzl__future_0_16_0_dirty//:pkg",
    "futures": "@examples_checked_in_requirements_bzl__futures_3_2_0//:pkg",
    "futures:dirty": "@examples_checked_in_requirements_bzl__futures_3_2_0_dirty//:pkg",
    "gapic-google-cloud-datastore-v1": "@examples_checked_in_requirements_bzl__gapic_google_cloud_datastore_v1_0_15_3//:pkg",
    "gapic-google-cloud-datastore-v1:dirty": "@examples_checked_in_requirements_bzl__gapic_google_cloud_datastore_v1_0_15_3_dirty//:pkg",
    "gapic-google-cloud-error-reporting-v1beta1": "@examples_checked_in_requirements_bzl__gapic_google_cloud_error_reporting_v1beta1_0_15_3//:pkg",
    "gapic-google-cloud-error-reporting-v1beta1:dirty": "@examples_checked_in_requirements_bzl__gapic_google_cloud_error_reporting_v1beta1_0_15_3_dirty//:pkg",
    "gapic-google-cloud-logging-v2": "@examples_checked_in_requirements_bzl__gapic_google_cloud_logging_v2_0_91_3//:pkg",
    "gapic-google-cloud-logging-v2:dirty": "@examples_checked_in_requirements_bzl__gapic_google_cloud_logging_v2_0_91_3_dirty//:pkg",
    "google-api-core": "@examples_checked_in_requirements_bzl__google_api_core_0_1_4//:pkg",
    "google-api-core:dirty": "@examples_checked_in_requirements_bzl__google_api_core_0_1_4_dirty//:pkg",
    "google-api-core[grpc]": "@examples_checked_in_requirements_bzl__google_api_core_0_1_4//:grpc",
    "google-api-core:dirty[grpc]": "@examples_checked_in_requirements_bzl__google_api_core_0_1_4_dirty//:grpc",
    "google-auth": "@examples_checked_in_requirements_bzl__google_auth_1_5_1//:pkg",
    "google-auth:dirty": "@examples_checked_in_requirements_bzl__google_auth_1_5_1_dirty//:pkg",
    "google-cloud": "@examples_checked_in_requirements_bzl__google_cloud_0_29_0//:pkg",
    "google-cloud:dirty": "@examples_checked_in_requirements_bzl__google_cloud_0_29_0_dirty//:pkg",
    "google-cloud-bigquery": "@examples_checked_in_requirements_bzl__google_cloud_bigquery_0_28_0//:pkg",
    "google-cloud-bigquery:dirty": "@examples_checked_in_requirements_bzl__google_cloud_bigquery_0_28_0_dirty//:pkg",
    "google-cloud-bigtable": "@examples_checked_in_requirements_bzl__google_cloud_bigtable_0_28_1//:pkg",
    "google-cloud-bigtable:dirty": "@examples_checked_in_requirements_bzl__google_cloud_bigtable_0_28_1_dirty//:pkg",
    "google-cloud-core": "@examples_checked_in_requirements_bzl__google_cloud_core_0_28_1//:pkg",
    "google-cloud-core:dirty": "@examples_checked_in_requirements_bzl__google_cloud_core_0_28_1_dirty//:pkg",
    "google-cloud-core[grpc]": "@examples_checked_in_requirements_bzl__google_cloud_core_0_28_1//:grpc",
    "google-cloud-core:dirty[grpc]": "@examples_checked_in_requirements_bzl__google_cloud_core_0_28_1_dirty//:grpc",
    "google-cloud-datastore": "@examples_checked_in_requirements_bzl__google_cloud_datastore_1_4_0//:pkg",
    "google-cloud-datastore:dirty": "@examples_checked_in_requirements_bzl__google_cloud_datastore_1_4_0_dirty//:pkg",
    "google-cloud-dns": "@examples_checked_in_requirements_bzl__google_cloud_dns_0_28_0//:pkg",
    "google-cloud-dns:dirty": "@examples_checked_in_requirements_bzl__google_cloud_dns_0_28_0_dirty//:pkg",
    "google-cloud-error-reporting": "@examples_checked_in_requirements_bzl__google_cloud_error_reporting_0_28_0//:pkg",
    "google-cloud-error-reporting:dirty": "@examples_checked_in_requirements_bzl__google_cloud_error_reporting_0_28_0_dirty//:pkg",
    "google-cloud-firestore": "@examples_checked_in_requirements_bzl__google_cloud_firestore_0_28_0//:pkg",
    "google-cloud-firestore:dirty": "@examples_checked_in_requirements_bzl__google_cloud_firestore_0_28_0_dirty//:pkg",
    "google-cloud-language": "@examples_checked_in_requirements_bzl__google_cloud_language_0_31_0//:pkg",
    "google-cloud-language:dirty": "@examples_checked_in_requirements_bzl__google_cloud_language_0_31_0_dirty//:pkg",
    "google-cloud-logging": "@examples_checked_in_requirements_bzl__google_cloud_logging_1_4_0//:pkg",
    "google-cloud-logging:dirty": "@examples_checked_in_requirements_bzl__google_cloud_logging_1_4_0_dirty//:pkg",
    "google-cloud-monitoring": "@examples_checked_in_requirements_bzl__google_cloud_monitoring_0_28_1//:pkg",
    "google-cloud-monitoring:dirty": "@examples_checked_in_requirements_bzl__google_cloud_monitoring_0_28_1_dirty//:pkg",
    "google-cloud-pubsub": "@examples_checked_in_requirements_bzl__google_cloud_pubsub_0_29_4//:pkg",
    "google-cloud-pubsub:dirty": "@examples_checked_in_requirements_bzl__google_cloud_pubsub_0_29_4_dirty//:pkg",
    "google-cloud-resource-manager": "@examples_checked_in_requirements_bzl__google_cloud_resource_manager_0_28_1//:pkg",
    "google-cloud-resource-manager:dirty": "@examples_checked_in_requirements_bzl__google_cloud_resource_manager_0_28_1_dirty//:pkg",
    "google-cloud-runtimeconfig": "@examples_checked_in_requirements_bzl__google_cloud_runtimeconfig_0_28_1//:pkg",
    "google-cloud-runtimeconfig:dirty": "@examples_checked_in_requirements_bzl__google_cloud_runtimeconfig_0_28_1_dirty//:pkg",
    "google-cloud-spanner": "@examples_checked_in_requirements_bzl__google_cloud_spanner_0_29_0//:pkg",
    "google-cloud-spanner:dirty": "@examples_checked_in_requirements_bzl__google_cloud_spanner_0_29_0_dirty//:pkg",
    "google-cloud-speech": "@examples_checked_in_requirements_bzl__google_cloud_speech_0_30_0//:pkg",
    "google-cloud-speech:dirty": "@examples_checked_in_requirements_bzl__google_cloud_speech_0_30_0_dirty//:pkg",
    "google-cloud-storage": "@examples_checked_in_requirements_bzl__google_cloud_storage_1_6_0//:pkg",
    "google-cloud-storage:dirty": "@examples_checked_in_requirements_bzl__google_cloud_storage_1_6_0_dirty//:pkg",
    "google-cloud-trace": "@examples_checked_in_requirements_bzl__google_cloud_trace_0_16_0//:pkg",
    "google-cloud-trace:dirty": "@examples_checked_in_requirements_bzl__google_cloud_trace_0_16_0_dirty//:pkg",
    "google-cloud-translate": "@examples_checked_in_requirements_bzl__google_cloud_translate_1_3_1//:pkg",
    "google-cloud-translate:dirty": "@examples_checked_in_requirements_bzl__google_cloud_translate_1_3_1_dirty//:pkg",
    "google-cloud-videointelligence": "@examples_checked_in_requirements_bzl__google_cloud_videointelligence_0_28_0//:pkg",
    "google-cloud-videointelligence:dirty": "@examples_checked_in_requirements_bzl__google_cloud_videointelligence_0_28_0_dirty//:pkg",
    "google-cloud-vision": "@examples_checked_in_requirements_bzl__google_cloud_vision_0_28_0//:pkg",
    "google-cloud-vision:dirty": "@examples_checked_in_requirements_bzl__google_cloud_vision_0_28_0_dirty//:pkg",
    "google-gax": "@examples_checked_in_requirements_bzl__google_gax_0_15_16//:pkg",
    "google-gax:dirty": "@examples_checked_in_requirements_bzl__google_gax_0_15_16_dirty//:pkg",
    "google-resumable-media": "@examples_checked_in_requirements_bzl__google_resumable_media_0_3_1//:pkg",
    "google-resumable-media:dirty": "@examples_checked_in_requirements_bzl__google_resumable_media_0_3_1_dirty//:pkg",
    "google-resumable-media[requests]": "@examples_checked_in_requirements_bzl__google_resumable_media_0_3_1//:requests",
    "google-resumable-media:dirty[requests]": "@examples_checked_in_requirements_bzl__google_resumable_media_0_3_1_dirty//:requests",
    "googleapis-common-protos": "@examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3//:pkg",
    "googleapis-common-protos:dirty": "@examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3_dirty//:pkg",
    "googleapis-common-protos[grpc]": "@examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3//:grpc",
    "googleapis-common-protos:dirty[grpc]": "@examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3_dirty//:grpc",
    "grpc-google-iam-v1": "@examples_checked_in_requirements_bzl__grpc_google_iam_v1_0_11_4//:pkg",
    "grpc-google-iam-v1:dirty": "@examples_checked_in_requirements_bzl__grpc_google_iam_v1_0_11_4_dirty//:pkg",
    "grpcio": "@examples_checked_in_requirements_bzl__grpcio_1_16_0//:pkg",
    "grpcio:dirty": "@examples_checked_in_requirements_bzl__grpcio_1_16_0_dirty//:pkg",
    "h5py": "@examples_checked_in_requirements_bzl__h5py_2_8_0//:pkg",
    "h5py:dirty": "@examples_checked_in_requirements_bzl__h5py_2_8_0_dirty//:pkg",
    "httplib2": "@examples_checked_in_requirements_bzl__httplib2_0_11_3//:pkg",
    "httplib2:dirty": "@examples_checked_in_requirements_bzl__httplib2_0_11_3_dirty//:pkg",
    "idna": "@examples_checked_in_requirements_bzl__idna_2_7//:pkg",
    "idna:dirty": "@examples_checked_in_requirements_bzl__idna_2_7_dirty//:pkg",
    "jmespath": "@examples_checked_in_requirements_bzl__jmespath_0_9_3//:pkg",
    "jmespath:dirty": "@examples_checked_in_requirements_bzl__jmespath_0_9_3_dirty//:pkg",
    "keras": "@examples_checked_in_requirements_bzl__Keras_2_2_2//:pkg",
    "keras:dirty": "@examples_checked_in_requirements_bzl__Keras_2_2_2_dirty//:pkg",
    "keras-applications": "@examples_checked_in_requirements_bzl__Keras_Applications_1_0_4//:pkg",
    "keras-applications:dirty": "@examples_checked_in_requirements_bzl__Keras_Applications_1_0_4_dirty//:pkg",
    "keras-preprocessing": "@examples_checked_in_requirements_bzl__Keras_Preprocessing_1_0_2//:pkg",
    "keras-preprocessing:dirty": "@examples_checked_in_requirements_bzl__Keras_Preprocessing_1_0_2_dirty//:pkg",
    "mock": "@examples_checked_in_requirements_bzl__mock_2_0_0//:pkg",
    "mock:dirty": "@examples_checked_in_requirements_bzl__mock_2_0_0_dirty//:pkg",
    "more-itertools": "@examples_checked_in_requirements_bzl__more_itertools_4_3_0//:pkg",
    "more-itertools:dirty": "@examples_checked_in_requirements_bzl__more_itertools_4_3_0_dirty//:pkg",
    "numpy": "@examples_checked_in_requirements_bzl__numpy_1_14_0//:pkg",
    "numpy:dirty": "@examples_checked_in_requirements_bzl__numpy_1_14_0_dirty//:pkg",
    "oauth2client": "@examples_checked_in_requirements_bzl__oauth2client_3_0_0//:pkg",
    "oauth2client:dirty": "@examples_checked_in_requirements_bzl__oauth2client_3_0_0_dirty//:pkg",
    "pathlib2": "@examples_checked_in_requirements_bzl__pathlib2_2_3_2//:pkg",
    "pathlib2:dirty": "@examples_checked_in_requirements_bzl__pathlib2_2_3_2_dirty//:pkg",
    "pbr": "@examples_checked_in_requirements_bzl__pbr_5_1_0//:pkg",
    "pbr:dirty": "@examples_checked_in_requirements_bzl__pbr_5_1_0_dirty//:pkg",
    "pip": "@examples_checked_in_requirements_bzl__pip_9_0_0//:pkg",
    "pip:dirty": "@examples_checked_in_requirements_bzl__pip_9_0_0_dirty//:pkg",
    "pluggy": "@examples_checked_in_requirements_bzl__pluggy_0_8_0//:pkg",
    "pluggy:dirty": "@examples_checked_in_requirements_bzl__pluggy_0_8_0_dirty//:pkg",
    "ply": "@examples_checked_in_requirements_bzl__ply_3_8//:pkg",
    "ply:dirty": "@examples_checked_in_requirements_bzl__ply_3_8_dirty//:pkg",
    "proto-google-cloud-datastore-v1": "@examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4//:pkg",
    "proto-google-cloud-datastore-v1:dirty": "@examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4_dirty//:pkg",
    "proto-google-cloud-datastore-v1[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4//:grpc",
    "proto-google-cloud-datastore-v1:dirty[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4_dirty//:grpc",
    "proto-google-cloud-error-reporting-v1beta1": "@examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3//:pkg",
    "proto-google-cloud-error-reporting-v1beta1:dirty": "@examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3_dirty//:pkg",
    "proto-google-cloud-error-reporting-v1beta1[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3//:grpc",
    "proto-google-cloud-error-reporting-v1beta1:dirty[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3_dirty//:grpc",
    "proto-google-cloud-logging-v2": "@examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3//:pkg",
    "proto-google-cloud-logging-v2:dirty": "@examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3_dirty//:pkg",
    "proto-google-cloud-logging-v2[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3//:grpc",
    "proto-google-cloud-logging-v2:dirty[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3_dirty//:grpc",
    "protobuf": "@examples_checked_in_requirements_bzl__protobuf_3_6_1//:pkg",
    "protobuf:dirty": "@examples_checked_in_requirements_bzl__protobuf_3_6_1_dirty//:pkg",
    "psutil": "@examples_checked_in_requirements_bzl__psutil_5_4_7//:pkg",
    "psutil:dirty": "@examples_checked_in_requirements_bzl__psutil_5_4_7_dirty//:pkg",
    "psutil[enum]": "@examples_checked_in_requirements_bzl__psutil_5_4_7//:enum",
    "psutil:dirty[enum]": "@examples_checked_in_requirements_bzl__psutil_5_4_7_dirty//:enum",
    "py": "@examples_checked_in_requirements_bzl__py_1_7_0//:pkg",
    "py:dirty": "@examples_checked_in_requirements_bzl__py_1_7_0_dirty//:pkg",
    "pyasn1": "@examples_checked_in_requirements_bzl__pyasn1_0_4_4//:pkg",
    "pyasn1:dirty": "@examples_checked_in_requirements_bzl__pyasn1_0_4_4_dirty//:pkg",
    "pyasn1-modules": "@examples_checked_in_requirements_bzl__pyasn1_modules_0_2_2//:pkg",
    "pyasn1-modules:dirty": "@examples_checked_in_requirements_bzl__pyasn1_modules_0_2_2_dirty//:pkg",
    "pytest": "@examples_checked_in_requirements_bzl__pytest_3_9_3//:pkg",
    "pytest:dirty": "@examples_checked_in_requirements_bzl__pytest_3_9_3_dirty//:pkg",
    "pytest-mock": "@examples_checked_in_requirements_bzl__pytest_mock_1_6_2//:pkg",
    "pytest-mock:dirty": "@examples_checked_in_requirements_bzl__pytest_mock_1_6_2_dirty//:pkg",
    "python-dateutil": "@examples_checked_in_requirements_bzl__python_dateutil_2_7_5//:pkg",
    "python-dateutil:dirty": "@examples_checked_in_requirements_bzl__python_dateutil_2_7_5_dirty//:pkg",
    "pytz": "@examples_checked_in_requirements_bzl__pytz_2018_7//:pkg",
    "pytz:dirty": "@examples_checked_in_requirements_bzl__pytz_2018_7_dirty//:pkg",
    "pyyaml": "@examples_checked_in_requirements_bzl__PyYAML_3_13//:pkg",
    "pyyaml:dirty": "@examples_checked_in_requirements_bzl__PyYAML_3_13_dirty//:pkg",
    "requests": "@examples_checked_in_requirements_bzl__requests_2_20_0//:pkg",
    "requests:dirty": "@examples_checked_in_requirements_bzl__requests_2_20_0_dirty//:pkg",
    "rsa": "@examples_checked_in_requirements_bzl__rsa_4_0//:pkg",
    "rsa:dirty": "@examples_checked_in_requirements_bzl__rsa_4_0_dirty//:pkg",
    "scandir": "@examples_checked_in_requirements_bzl__scandir_1_9_0//:pkg",
    "scandir:dirty": "@examples_checked_in_requirements_bzl__scandir_1_9_0_dirty//:pkg",
    "scikit-learn": "@examples_checked_in_requirements_bzl__scikit_learn_0_17_1//:pkg",
    "scikit-learn:dirty": "@examples_checked_in_requirements_bzl__scikit_learn_0_17_1_dirty//:pkg",
    "scipy": "@examples_checked_in_requirements_bzl__scipy_0_17_1//:pkg",
    "scipy:dirty": "@examples_checked_in_requirements_bzl__scipy_0_17_1_dirty//:pkg",
    "setuptools": "@examples_checked_in_requirements_bzl__setuptools_40_5_0//:pkg",
    "setuptools:dirty": "@examples_checked_in_requirements_bzl__setuptools_40_5_0_dirty//:pkg",
    "setuptools[certs]": "@examples_checked_in_requirements_bzl__setuptools_40_5_0//:certs",
    "setuptools:dirty[certs]": "@examples_checked_in_requirements_bzl__setuptools_40_5_0_dirty//:certs",
    "setuptools[ssl]": "@examples_checked_in_requirements_bzl__setuptools_40_5_0//:ssl",
    "setuptools:dirty[ssl]": "@examples_checked_in_requirements_bzl__setuptools_40_5_0_dirty//:ssl",
    "setuptools-scm": "@examples_checked_in_requirements_bzl__setuptools_scm_2_0_0//:pkg",
    "setuptools-scm:dirty": "@examples_checked_in_requirements_bzl__setuptools_scm_2_0_0_dirty//:pkg",
    "six": "@examples_checked_in_requirements_bzl__six_1_11_0//:pkg",
    "six:dirty": "@examples_checked_in_requirements_bzl__six_1_11_0_dirty//:pkg",
    "urllib3": "@examples_checked_in_requirements_bzl__urllib3_1_24//:pkg",
    "urllib3:dirty": "@examples_checked_in_requirements_bzl__urllib3_1_24_dirty//:pkg",
}

all_requirements = _requirements.values()
requirements_map = _requirements

def requirement_repo(name):
    return requirement(name).split(":")[0]

def requirement(name, binary = None):
    key = name.lower()
    if key not in _requirements:
        fail("Could not find pip-provided dependency: '%s'" % name)
    if binary:
        return _requirements[key].split(":")[0] + ":entrypoint_" + binary
    return _requirements[key]

def pip_install():
    all_libs = {
        "atomicwrites": {
            "name": "examples_checked_in_requirements_bzl__atomicwrites_1_2_1",
            "version": "1.2.1",
            "wheel_name": "atomicwrites-1.2.1-py2.py3-none-any.whl",
        },
        "attrs": {
            "name": "examples_checked_in_requirements_bzl__attrs_18_2_0",
            "version": "18.2.0",
            "wheel_name": "attrs-18.2.0-py2.py3-none-any.whl",
        },
        "backports.functools-lru-cache": {
            "name": "examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5",
            "version": "1.5",
            "wheel_name": "backports.functools_lru_cache-1.5-py2.py3-none-any.whl",
        },
        "backports.ssl-match-hostname": {
            "name": "examples_checked_in_requirements_bzl__backports_ssl_match_hostname_3_5_0_1",
            "version": "3.5.0.1",
            "wheel_name": "backports.ssl_match_hostname-3.5.0.1-py2-none-any.whl",
        },
        "botocore": {
            "name": "examples_checked_in_requirements_bzl__botocore_1_12_33",
            "version": "1.12.33",
            "wheel_name": "botocore-1.12.33-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["docutils", "jmespath", "python-dateutil", "six", "urllib3"],
        },
        "cachetools": {
            "name": "examples_checked_in_requirements_bzl__cachetools_2_1_0",
            "version": "2.1.0",
            "wheel_name": "cachetools-2.1.0-py2.py3-none-any.whl",
        },
        "certifi": {
            "name": "examples_checked_in_requirements_bzl__certifi_2018_10_15",
            "version": "2018.10.15",
            "wheel_name": "certifi-2018.10.15-py2.py3-none-any.whl",
        },
        "chardet": {
            "name": "examples_checked_in_requirements_bzl__chardet_3_0_4",
            "version": "3.0.4",
            "wheel_name": "chardet-3.0.4-py2.py3-none-any.whl",
        },
        "dill": {
            "name": "examples_checked_in_requirements_bzl__dill_0_2_8_2",
            "version": "0.2.8.2",
            "wheel_name": "dill-0.2.8.2-py2-none-any.whl",
        },
        "docutils": {
            "name": "examples_checked_in_requirements_bzl__docutils_0_14",
            "version": "0.14",
            "wheel_name": "docutils-0.14-py2-none-any.whl",
        },
        "enum34": {
            "name": "examples_checked_in_requirements_bzl__enum34_1_1_6",
            "version": "1.1.6",
            "wheel_name": "enum34-1.1.6-py2-none-any.whl",
        },
        "funcsigs": {
            "name": "examples_checked_in_requirements_bzl__funcsigs_1_0_2",
            "version": "1.0.2",
            "wheel_name": "funcsigs-1.0.2-py2.py3-none-any.whl",
        },
        "future": {
            "name": "examples_checked_in_requirements_bzl__future_0_16_0",
            "version": "0.16.0",
            "wheel_name": "future-0.16.0-py2-none-any.whl",
        },
        "futures": {
            "name": "examples_checked_in_requirements_bzl__futures_3_2_0",
            "version": "3.2.0",
            "wheel_name": "futures-3.2.0-py2-none-any.whl",
        },
        "gapic-google-cloud-datastore-v1": {
            "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_datastore_v1_0_15_3",
            "version": "0.15.3",
            "wheel_name": "gapic_google_cloud_datastore_v1-0.15.3-py2-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "gapic-google-cloud-error-reporting-v1beta1": {
            "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_error_reporting_v1beta1_0_15_3",
            "version": "0.15.3",
            "wheel_name": "gapic_google_cloud_error_reporting_v1beta1-0.15.3-py2-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-error-reporting-v1beta1", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "gapic-google-cloud-logging-v2": {
            "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_logging_v2_0_91_3",
            "version": "0.91.3",
            "wheel_name": "gapic_google_cloud_logging_v2-0.91.3-py2-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-api-core": {
            "name": "examples_checked_in_requirements_bzl__google_api_core_0_1_4",
            "version": "0.1.4",
            "wheel_name": "google_api_core-0.1.4-py2.py3-none-any.whl",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-auth", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-auth": {
            "name": "examples_checked_in_requirements_bzl__google_auth_1_5_1",
            "version": "1.5.1",
            "wheel_name": "google_auth-1.5.1-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "pyasn1", "pyasn1-modules", "rsa", "six"],
        },
        "google-cloud": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_0_29_0",
            "version": "0.29.0",
            "wheel_name": "google_cloud-0.29.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-datastore-v1", "gapic-google-cloud-error-reporting-v1beta1", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-bigquery", "google-cloud-bigtable", "google-cloud-core", "google-cloud-datastore", "google-cloud-dns", "google-cloud-error-reporting", "google-cloud-firestore", "google-cloud-language", "google-cloud-logging", "google-cloud-monitoring", "google-cloud-pubsub", "google-cloud-resource-manager", "google-cloud-runtimeconfig", "google-cloud-spanner", "google-cloud-speech", "google-cloud-storage", "google-cloud-trace", "google-cloud-translate", "google-cloud-videointelligence", "google-cloud-vision", "google-gax", "google-resumable-media", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "proto-google-cloud-error-reporting-v1beta1", "proto-google-cloud-logging-v2", "protobuf", "psutil", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-bigquery": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_bigquery_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_bigquery-0.28.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-resumable-media", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-bigtable": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_bigtable_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_bigtable-0.28.1-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-core": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_core_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_core-0.28.1-py2.py3-none-any.whl",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-datastore": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_datastore_1_4_0",
            "version": "1.4.0",
            "wheel_name": "google_cloud_datastore-1.4.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-datastore-v1", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-dns": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_dns_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_dns-0.28.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-error-reporting": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_error_reporting_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_error_reporting-0.28.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-error-reporting-v1beta1", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-core", "google-cloud-logging", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-error-reporting-v1beta1", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-firestore": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_firestore_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_firestore-0.28.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-language": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_language_0_31_0",
            "version": "0.31.0",
            "wheel_name": "google_cloud_language-0.31.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "enum34", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "grpcio", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-logging": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_logging_1_4_0",
            "version": "1.4.0",
            "wheel_name": "google_cloud_logging-1.4.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-monitoring": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_monitoring_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_monitoring-0.28.1-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-pubsub": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_pubsub_0_29_4",
            "version": "0.29.4",
            "wheel_name": "google_cloud_pubsub-0.29.4-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "enum34", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "idna", "protobuf", "psutil", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-resource-manager": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_resource_manager_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_resource_manager-0.28.1-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-runtimeconfig": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_runtimeconfig_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_runtimeconfig-0.28.1-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-spanner": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_spanner_0_29_0",
            "version": "0.29.0",
            "wheel_name": "google_cloud_spanner-0.29.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-speech": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_speech_0_30_0",
            "version": "0.30.0",
            "wheel_name": "google_cloud_speech-0.30.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-storage": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_storage_1_6_0",
            "version": "1.6.0",
            "wheel_name": "google_cloud_storage-1.6.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-resumable-media", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-trace": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_trace_0_16_0",
            "version": "0.16.0",
            "wheel_name": "google_cloud_trace-0.16.0-py2-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-translate": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_translate_1_3_1",
            "version": "1.3.1",
            "wheel_name": "google_cloud_translate-1.3.1-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-videointelligence": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_videointelligence_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_videointelligence-0.28.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-vision": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_vision_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_vision-0.28.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-gax": {
            "name": "examples_checked_in_requirements_bzl__google_gax_0_15_16",
            "version": "0.15.16",
            "wheel_name": "google_gax-0.15.16-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-resumable-media": {
            "name": "examples_checked_in_requirements_bzl__google_resumable_media_0_3_1",
            "version": "0.3.1",
            "wheel_name": "google_resumable_media-0.3.1-py2.py3-none-any.whl",
            "extras": ["requests"],
            "transitive_runtime_deps": ["six"],
        },
        "googleapis-common-protos": {
            "name": "examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3",
            "version": "1.5.3",
            "wheel_name": "googleapis_common_protos-1.5.3-py2-none-any.whl",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["protobuf", "setuptools", "six"],
        },
        "grpc-google-iam-v1": {
            "name": "examples_checked_in_requirements_bzl__grpc_google_iam_v1_0_11_4",
            "version": "0.11.4",
            "wheel_name": "grpc_google_iam_v1-0.11.4-py2-none-any.whl",
            "transitive_runtime_deps": ["enum34", "futures", "googleapis-common-protos", "grpcio", "protobuf", "setuptools", "six"],
        },
        "grpcio": {
            "name": "examples_checked_in_requirements_bzl__grpcio_1_16_0",
            "version": "1.16.0",
            "wheel_name": "grpcio-1.16.0-cp27-cp27mu-manylinux1_x86_64.whl",
            "transitive_runtime_deps": ["enum34", "futures", "six"],
        },
        "h5py": {
            "name": "examples_checked_in_requirements_bzl__h5py_2_8_0",
            "version": "2.8.0",
            "wheel_name": "h5py-2.8.0-cp27-cp27mu-manylinux1_x86_64.whl",
            "transitive_runtime_deps": ["numpy", "six"],
        },
        "httplib2": {
            "name": "examples_checked_in_requirements_bzl__httplib2_0_11_3",
            "version": "0.11.3",
            "wheel_name": "httplib2-0.11.3-py2-none-any.whl",
        },
        "idna": {
            "name": "examples_checked_in_requirements_bzl__idna_2_7",
            "version": "2.7",
            "wheel_name": "idna-2.7-py2.py3-none-any.whl",
        },
        "jmespath": {
            "name": "examples_checked_in_requirements_bzl__jmespath_0_9_3",
            "version": "0.9.3",
            "wheel_name": "jmespath-0.9.3-py2.py3-none-any.whl",
        },
        "keras": {
            "name": "examples_checked_in_requirements_bzl__Keras_2_2_2",
            "version": "2.2.2",
            "wheel_name": "Keras-2.2.2-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
        },
        "keras-applications": {
            "name": "examples_checked_in_requirements_bzl__Keras_Applications_1_0_4",
            "version": "1.0.4",
            "wheel_name": "Keras_Applications-1.0.4-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
        },
        "keras-preprocessing": {
            "name": "examples_checked_in_requirements_bzl__Keras_Preprocessing_1_0_2",
            "version": "1.0.2",
            "wheel_name": "Keras_Preprocessing-1.0.2-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
        },
        "mock": {
            "name": "examples_checked_in_requirements_bzl__mock_2_0_0",
            "version": "2.0.0",
            "wheel_name": "mock-2.0.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["funcsigs", "pbr", "six"],
        },
        "more-itertools": {
            "name": "examples_checked_in_requirements_bzl__more_itertools_4_3_0",
            "version": "4.3.0",
            "wheel_name": "more_itertools-4.3.0-py2-none-any.whl",
            "transitive_runtime_deps": ["six"],
        },
        "numpy": {
            "name": "examples_checked_in_requirements_bzl__numpy_1_14_0",
            "version": "1.14.0",
            "wheel_name": "numpy-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl",
        },
        "oauth2client": {
            "name": "examples_checked_in_requirements_bzl__oauth2client_3_0_0",
            "version": "3.0.0",
            "wheel_name": "oauth2client-3.0.0-py2-none-any.whl",
            "transitive_runtime_deps": ["httplib2", "pyasn1", "pyasn1-modules", "rsa", "six"],
        },
        "pathlib2": {
            "name": "examples_checked_in_requirements_bzl__pathlib2_2_3_2",
            "version": "2.3.2",
            "wheel_name": "pathlib2-2.3.2-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["scandir", "six"],
        },
        "pbr": {
            "name": "examples_checked_in_requirements_bzl__pbr_5_1_0",
            "version": "5.1.0",
            "wheel_name": "pbr-5.1.0-py2.py3-none-any.whl",
        },
        "pip": {
            "name": "examples_checked_in_requirements_bzl__pip_9_0_0",
            "version": "9.0.0",
            "wheel_name": "pip-9.0.0-py2.py3-none-any.whl",
        },
        "pluggy": {
            "name": "examples_checked_in_requirements_bzl__pluggy_0_8_0",
            "version": "0.8.0",
            "wheel_name": "pluggy-0.8.0-py2.py3-none-any.whl",
        },
        "ply": {
            "name": "examples_checked_in_requirements_bzl__ply_3_8",
            "version": "3.8",
            "wheel_name": "ply-3.8-py2.py3-none-any.whl",
        },
        "proto-google-cloud-datastore-v1": {
            "name": "examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4",
            "version": "0.90.4",
            "wheel_name": "proto_google_cloud_datastore_v1-0.90.4-py2-none-any.whl",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
        },
        "proto-google-cloud-error-reporting-v1beta1": {
            "name": "examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3",
            "version": "0.15.3",
            "wheel_name": "proto_google_cloud_error_reporting_v1beta1-0.15.3-py2-none-any.whl",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
        },
        "proto-google-cloud-logging-v2": {
            "name": "examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3",
            "version": "0.91.3",
            "wheel_name": "proto_google_cloud_logging_v2-0.91.3-py2-none-any.whl",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
        },
        "protobuf": {
            "name": "examples_checked_in_requirements_bzl__protobuf_3_6_1",
            "version": "3.6.1",
            "wheel_name": "protobuf-3.6.1-cp27-cp27mu-manylinux1_x86_64.whl",
            "transitive_runtime_deps": ["setuptools", "six"],
        },
        "psutil": {
            "name": "examples_checked_in_requirements_bzl__psutil_5_4_7",
            "version": "5.4.7",
            "wheel_name": "psutil-5.4.7-cp27-cp27mu-linux_x86_64.whl",
            "extras": ["enum"],
        },
        "py": {
            "name": "examples_checked_in_requirements_bzl__py_1_7_0",
            "version": "1.7.0",
            "wheel_name": "py-1.7.0-py2.py3-none-any.whl",
        },
        "pyasn1": {
            "name": "examples_checked_in_requirements_bzl__pyasn1_0_4_4",
            "version": "0.4.4",
            "wheel_name": "pyasn1-0.4.4-py2.py3-none-any.whl",
        },
        "pyasn1-modules": {
            "name": "examples_checked_in_requirements_bzl__pyasn1_modules_0_2_2",
            "version": "0.2.2",
            "wheel_name": "pyasn1_modules-0.2.2-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["pyasn1"],
        },
        "pytest": {
            "name": "examples_checked_in_requirements_bzl__pytest_3_9_3",
            "version": "3.9.3",
            "wheel_name": "pytest-3.9.3-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["atomicwrites", "attrs", "funcsigs", "more-itertools", "pathlib2", "pluggy", "py", "scandir", "setuptools", "six"],
        },
        "pytest-mock": {
            "name": "examples_checked_in_requirements_bzl__pytest_mock_1_6_2",
            "version": "1.6.2",
            "wheel_name": "pytest_mock-1.6.2-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["atomicwrites", "attrs", "funcsigs", "mock", "more-itertools", "pathlib2", "pbr", "pluggy", "py", "pytest", "scandir", "setuptools", "six"],
        },
        "python-dateutil": {
            "name": "examples_checked_in_requirements_bzl__python_dateutil_2_7_5",
            "version": "2.7.5",
            "wheel_name": "python_dateutil-2.7.5-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["six"],
        },
        "pytz": {
            "name": "examples_checked_in_requirements_bzl__pytz_2018_7",
            "version": "2018.7",
            "wheel_name": "pytz-2018.7-py2.py3-none-any.whl",
        },
        "pyyaml": {
            "name": "examples_checked_in_requirements_bzl__PyYAML_3_13",
            "version": "3.13",
            "wheel_name": "PyYAML-3.13-cp27-cp27mu-linux_x86_64.whl",
        },
        "requests": {
            "name": "examples_checked_in_requirements_bzl__requests_2_20_0",
            "version": "2.20.0",
            "wheel_name": "requests-2.20.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["certifi", "chardet", "idna", "urllib3"],
        },
        "rsa": {
            "name": "examples_checked_in_requirements_bzl__rsa_4_0",
            "version": "4.0",
            "wheel_name": "rsa-4.0-py2.py3-none-any.whl",
            "transitive_runtime_deps": ["pyasn1"],
        },
        "scandir": {
            "name": "examples_checked_in_requirements_bzl__scandir_1_9_0",
            "version": "1.9.0",
            "wheel_name": "scandir-1.9.0-cp27-cp27mu-linux_x86_64.whl",
        },
        "scikit-learn": {
            "name": "examples_checked_in_requirements_bzl__scikit_learn_0_17_1",
            "version": "0.17.1",
            "wheel_name": "scikit_learn-0.17.1-cp27-cp27mu-manylinux1_x86_64.whl",
        },
        "scipy": {
            "name": "examples_checked_in_requirements_bzl__scipy_0_17_1",
            "version": "0.17.1",
            "wheel_name": "scipy-0.17.1-cp27-cp27mu-manylinux1_x86_64.whl",
        },
        "setuptools": {
            "name": "examples_checked_in_requirements_bzl__setuptools_40_5_0",
            "version": "40.5.0",
            "wheel_name": "setuptools-40.5.0-py2.py3-none-any.whl",
            "extras": ["certs", "ssl"],
        },
        "setuptools-scm": {
            "name": "examples_checked_in_requirements_bzl__setuptools_scm_2_0_0",
            "version": "2.0.0",
            "wheel_name": "setuptools_scm-2.0.0-py2.py3-none-any.whl",
        },
        "six": {
            "name": "examples_checked_in_requirements_bzl__six_1_11_0",
            "version": "1.11.0",
            "wheel_name": "six-1.11.0-py2.py3-none-any.whl",
        },
        "urllib3": {
            "name": "examples_checked_in_requirements_bzl__urllib3_1_24",
            "version": "1.24",
            "wheel_name": "urllib3-1.24-py2.py3-none-any.whl",
        },
    }

    for key, attributes in all_libs.items():
        whl_library(
            key = key,
            all_libs = all_libs,
            python = "@python2//:bin/python",
            **attributes
        )
