# Install pip requirements.
#
# Generated from /home/lpeltonen/go/src/github.com/bazelbuild/rules_python/examples/checked_in_requirements_bzl/requirements.txt
# Generated from /home/lpeltonen/go/src/github.com/bazelbuild/rules_python/examples/checked_in_requirements_bzl/requirements-2.txt

load("@examples_checked_in_requirements_bzl//python:whl.bzl", "whl_library")

_requirements = {
    "atomicwrites": "@examples_checked_in_requirements_bzl__atomicwrites_1_2_1//:pkg",
    "atomicwrites:dirty": "@examples_checked_in_requirements_bzl__atomicwrites_1_2_1_dirty//:pkg",
    "attrs": "@examples_checked_in_requirements_bzl__attrs_18_2_0//:pkg",
    "attrs:dirty": "@examples_checked_in_requirements_bzl__attrs_18_2_0_dirty//:pkg",
    "backports.functools-lru-cache": "@examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5//:pkg",
    "backports.functools-lru-cache:dirty": "@examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5_dirty//:pkg",
    "backports.ssl-match-hostname": "@examples_checked_in_requirements_bzl__backports_ssl_match_hostname_3_5_0_1//:pkg",
    "backports.ssl-match-hostname:dirty": "@examples_checked_in_requirements_bzl__backports_ssl_match_hostname_3_5_0_1_dirty//:pkg",
    "botocore": "@examples_checked_in_requirements_bzl__botocore_1_12_18//:pkg",
    "botocore:dirty": "@examples_checked_in_requirements_bzl__botocore_1_12_18_dirty//:pkg",
    "cachetools": "@examples_checked_in_requirements_bzl__cachetools_2_1_0//:pkg",
    "cachetools:dirty": "@examples_checked_in_requirements_bzl__cachetools_2_1_0_dirty//:pkg",
    "certifi": "@examples_checked_in_requirements_bzl__certifi_2018_8_24//:pkg",
    "certifi:dirty": "@examples_checked_in_requirements_bzl__certifi_2018_8_24_dirty//:pkg",
    "chardet": "@examples_checked_in_requirements_bzl__chardet_3_0_4//:pkg",
    "chardet:dirty": "@examples_checked_in_requirements_bzl__chardet_3_0_4_dirty//:pkg",
    "dill": "@examples_checked_in_requirements_bzl__dill_0_2_8_2//:pkg",
    "dill:dirty": "@examples_checked_in_requirements_bzl__dill_0_2_8_2_dirty//:pkg",
    "docutils": "@examples_checked_in_requirements_bzl__docutils_0_14//:pkg",
    "docutils:dirty": "@examples_checked_in_requirements_bzl__docutils_0_14_dirty//:pkg",
    "enum34": "@examples_checked_in_requirements_bzl__enum34_1_1_6//:pkg",
    "enum34:dirty": "@examples_checked_in_requirements_bzl__enum34_1_1_6_dirty//:pkg",
    "funcsigs": "@examples_checked_in_requirements_bzl__funcsigs_1_0_2//:pkg",
    "funcsigs:dirty": "@examples_checked_in_requirements_bzl__funcsigs_1_0_2_dirty//:pkg",
    "future": "@examples_checked_in_requirements_bzl__future_0_16_0//:pkg",
    "future:dirty": "@examples_checked_in_requirements_bzl__future_0_16_0_dirty//:pkg",
    "futures": "@examples_checked_in_requirements_bzl__futures_3_2_0//:pkg",
    "futures:dirty": "@examples_checked_in_requirements_bzl__futures_3_2_0_dirty//:pkg",
    "gapic-google-cloud-datastore-v1": "@examples_checked_in_requirements_bzl__gapic_google_cloud_datastore_v1_0_15_3//:pkg",
    "gapic-google-cloud-datastore-v1:dirty": "@examples_checked_in_requirements_bzl__gapic_google_cloud_datastore_v1_0_15_3_dirty//:pkg",
    "gapic-google-cloud-error-reporting-v1beta1": "@examples_checked_in_requirements_bzl__gapic_google_cloud_error_reporting_v1beta1_0_15_3//:pkg",
    "gapic-google-cloud-error-reporting-v1beta1:dirty": "@examples_checked_in_requirements_bzl__gapic_google_cloud_error_reporting_v1beta1_0_15_3_dirty//:pkg",
    "gapic-google-cloud-logging-v2": "@examples_checked_in_requirements_bzl__gapic_google_cloud_logging_v2_0_91_3//:pkg",
    "gapic-google-cloud-logging-v2:dirty": "@examples_checked_in_requirements_bzl__gapic_google_cloud_logging_v2_0_91_3_dirty//:pkg",
    "google-api-core": "@examples_checked_in_requirements_bzl__google_api_core_0_1_4//:pkg",
    "google-api-core:dirty": "@examples_checked_in_requirements_bzl__google_api_core_0_1_4_dirty//:pkg",
    "google-api-core[grpc]": "@examples_checked_in_requirements_bzl__google_api_core_0_1_4//:grpc",
    "google-api-core:dirty[grpc]": "@examples_checked_in_requirements_bzl__google_api_core_0_1_4_dirty//:grpc",
    "google-auth": "@examples_checked_in_requirements_bzl__google_auth_1_5_1//:pkg",
    "google-auth:dirty": "@examples_checked_in_requirements_bzl__google_auth_1_5_1_dirty//:pkg",
    "google-cloud": "@examples_checked_in_requirements_bzl__google_cloud_0_29_0//:pkg",
    "google-cloud:dirty": "@examples_checked_in_requirements_bzl__google_cloud_0_29_0_dirty//:pkg",
    "google-cloud-bigquery": "@examples_checked_in_requirements_bzl__google_cloud_bigquery_0_28_0//:pkg",
    "google-cloud-bigquery:dirty": "@examples_checked_in_requirements_bzl__google_cloud_bigquery_0_28_0_dirty//:pkg",
    "google-cloud-bigtable": "@examples_checked_in_requirements_bzl__google_cloud_bigtable_0_28_1//:pkg",
    "google-cloud-bigtable:dirty": "@examples_checked_in_requirements_bzl__google_cloud_bigtable_0_28_1_dirty//:pkg",
    "google-cloud-core": "@examples_checked_in_requirements_bzl__google_cloud_core_0_28_1//:pkg",
    "google-cloud-core:dirty": "@examples_checked_in_requirements_bzl__google_cloud_core_0_28_1_dirty//:pkg",
    "google-cloud-core[grpc]": "@examples_checked_in_requirements_bzl__google_cloud_core_0_28_1//:grpc",
    "google-cloud-core:dirty[grpc]": "@examples_checked_in_requirements_bzl__google_cloud_core_0_28_1_dirty//:grpc",
    "google-cloud-datastore": "@examples_checked_in_requirements_bzl__google_cloud_datastore_1_4_0//:pkg",
    "google-cloud-datastore:dirty": "@examples_checked_in_requirements_bzl__google_cloud_datastore_1_4_0_dirty//:pkg",
    "google-cloud-dns": "@examples_checked_in_requirements_bzl__google_cloud_dns_0_28_0//:pkg",
    "google-cloud-dns:dirty": "@examples_checked_in_requirements_bzl__google_cloud_dns_0_28_0_dirty//:pkg",
    "google-cloud-error-reporting": "@examples_checked_in_requirements_bzl__google_cloud_error_reporting_0_28_0//:pkg",
    "google-cloud-error-reporting:dirty": "@examples_checked_in_requirements_bzl__google_cloud_error_reporting_0_28_0_dirty//:pkg",
    "google-cloud-firestore": "@examples_checked_in_requirements_bzl__google_cloud_firestore_0_28_0//:pkg",
    "google-cloud-firestore:dirty": "@examples_checked_in_requirements_bzl__google_cloud_firestore_0_28_0_dirty//:pkg",
    "google-cloud-language": "@examples_checked_in_requirements_bzl__google_cloud_language_0_31_0//:pkg",
    "google-cloud-language:dirty": "@examples_checked_in_requirements_bzl__google_cloud_language_0_31_0_dirty//:pkg",
    "google-cloud-logging": "@examples_checked_in_requirements_bzl__google_cloud_logging_1_4_0//:pkg",
    "google-cloud-logging:dirty": "@examples_checked_in_requirements_bzl__google_cloud_logging_1_4_0_dirty//:pkg",
    "google-cloud-monitoring": "@examples_checked_in_requirements_bzl__google_cloud_monitoring_0_28_1//:pkg",
    "google-cloud-monitoring:dirty": "@examples_checked_in_requirements_bzl__google_cloud_monitoring_0_28_1_dirty//:pkg",
    "google-cloud-pubsub": "@examples_checked_in_requirements_bzl__google_cloud_pubsub_0_29_4//:pkg",
    "google-cloud-pubsub:dirty": "@examples_checked_in_requirements_bzl__google_cloud_pubsub_0_29_4_dirty//:pkg",
    "google-cloud-resource-manager": "@examples_checked_in_requirements_bzl__google_cloud_resource_manager_0_28_1//:pkg",
    "google-cloud-resource-manager:dirty": "@examples_checked_in_requirements_bzl__google_cloud_resource_manager_0_28_1_dirty//:pkg",
    "google-cloud-runtimeconfig": "@examples_checked_in_requirements_bzl__google_cloud_runtimeconfig_0_28_1//:pkg",
    "google-cloud-runtimeconfig:dirty": "@examples_checked_in_requirements_bzl__google_cloud_runtimeconfig_0_28_1_dirty//:pkg",
    "google-cloud-spanner": "@examples_checked_in_requirements_bzl__google_cloud_spanner_0_29_0//:pkg",
    "google-cloud-spanner:dirty": "@examples_checked_in_requirements_bzl__google_cloud_spanner_0_29_0_dirty//:pkg",
    "google-cloud-speech": "@examples_checked_in_requirements_bzl__google_cloud_speech_0_30_0//:pkg",
    "google-cloud-speech:dirty": "@examples_checked_in_requirements_bzl__google_cloud_speech_0_30_0_dirty//:pkg",
    "google-cloud-storage": "@examples_checked_in_requirements_bzl__google_cloud_storage_1_6_0//:pkg",
    "google-cloud-storage:dirty": "@examples_checked_in_requirements_bzl__google_cloud_storage_1_6_0_dirty//:pkg",
    "google-cloud-trace": "@examples_checked_in_requirements_bzl__google_cloud_trace_0_16_0//:pkg",
    "google-cloud-trace:dirty": "@examples_checked_in_requirements_bzl__google_cloud_trace_0_16_0_dirty//:pkg",
    "google-cloud-translate": "@examples_checked_in_requirements_bzl__google_cloud_translate_1_3_1//:pkg",
    "google-cloud-translate:dirty": "@examples_checked_in_requirements_bzl__google_cloud_translate_1_3_1_dirty//:pkg",
    "google-cloud-videointelligence": "@examples_checked_in_requirements_bzl__google_cloud_videointelligence_0_28_0//:pkg",
    "google-cloud-videointelligence:dirty": "@examples_checked_in_requirements_bzl__google_cloud_videointelligence_0_28_0_dirty//:pkg",
    "google-cloud-vision": "@examples_checked_in_requirements_bzl__google_cloud_vision_0_28_0//:pkg",
    "google-cloud-vision:dirty": "@examples_checked_in_requirements_bzl__google_cloud_vision_0_28_0_dirty//:pkg",
    "google-gax": "@examples_checked_in_requirements_bzl__google_gax_0_15_16//:pkg",
    "google-gax:dirty": "@examples_checked_in_requirements_bzl__google_gax_0_15_16_dirty//:pkg",
    "google-resumable-media": "@examples_checked_in_requirements_bzl__google_resumable_media_0_3_1//:pkg",
    "google-resumable-media:dirty": "@examples_checked_in_requirements_bzl__google_resumable_media_0_3_1_dirty//:pkg",
    "google-resumable-media[requests]": "@examples_checked_in_requirements_bzl__google_resumable_media_0_3_1//:requests",
    "google-resumable-media:dirty[requests]": "@examples_checked_in_requirements_bzl__google_resumable_media_0_3_1_dirty//:requests",
    "googleapis-common-protos": "@examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3//:pkg",
    "googleapis-common-protos:dirty": "@examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3_dirty//:pkg",
    "googleapis-common-protos[grpc]": "@examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3//:grpc",
    "googleapis-common-protos:dirty[grpc]": "@examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3_dirty//:grpc",
    "grpc-google-iam-v1": "@examples_checked_in_requirements_bzl__grpc_google_iam_v1_0_11_4//:pkg",
    "grpc-google-iam-v1:dirty": "@examples_checked_in_requirements_bzl__grpc_google_iam_v1_0_11_4_dirty//:pkg",
    "grpcio": "@examples_checked_in_requirements_bzl__grpcio_1_15_0//:pkg",
    "grpcio:dirty": "@examples_checked_in_requirements_bzl__grpcio_1_15_0_dirty//:pkg",
    "h5py": "@examples_checked_in_requirements_bzl__h5py_2_8_0//:pkg",
    "h5py:dirty": "@examples_checked_in_requirements_bzl__h5py_2_8_0_dirty//:pkg",
    "httplib2": "@examples_checked_in_requirements_bzl__httplib2_0_11_3//:pkg",
    "httplib2:dirty": "@examples_checked_in_requirements_bzl__httplib2_0_11_3_dirty//:pkg",
    "idna": "@examples_checked_in_requirements_bzl__idna_2_7//:pkg",
    "idna:dirty": "@examples_checked_in_requirements_bzl__idna_2_7_dirty//:pkg",
    "jmespath": "@examples_checked_in_requirements_bzl__jmespath_0_9_3//:pkg",
    "jmespath:dirty": "@examples_checked_in_requirements_bzl__jmespath_0_9_3_dirty//:pkg",
    "keras": "@examples_checked_in_requirements_bzl__Keras_2_2_2//:pkg",
    "keras:dirty": "@examples_checked_in_requirements_bzl__Keras_2_2_2_dirty//:pkg",
    "keras-applications": "@examples_checked_in_requirements_bzl__Keras_Applications_1_0_4//:pkg",
    "keras-applications:dirty": "@examples_checked_in_requirements_bzl__Keras_Applications_1_0_4_dirty//:pkg",
    "keras-preprocessing": "@examples_checked_in_requirements_bzl__Keras_Preprocessing_1_0_2//:pkg",
    "keras-preprocessing:dirty": "@examples_checked_in_requirements_bzl__Keras_Preprocessing_1_0_2_dirty//:pkg",
    "mock": "@examples_checked_in_requirements_bzl__mock_2_0_0//:pkg",
    "mock:dirty": "@examples_checked_in_requirements_bzl__mock_2_0_0_dirty//:pkg",
    "more-itertools": "@examples_checked_in_requirements_bzl__more_itertools_4_3_0//:pkg",
    "more-itertools:dirty": "@examples_checked_in_requirements_bzl__more_itertools_4_3_0_dirty//:pkg",
    "numpy": "@examples_checked_in_requirements_bzl__numpy_1_14_0//:pkg",
    "numpy:dirty": "@examples_checked_in_requirements_bzl__numpy_1_14_0_dirty//:pkg",
    "oauth2client": "@examples_checked_in_requirements_bzl__oauth2client_3_0_0//:pkg",
    "oauth2client:dirty": "@examples_checked_in_requirements_bzl__oauth2client_3_0_0_dirty//:pkg",
    "pathlib2": "@examples_checked_in_requirements_bzl__pathlib2_2_3_2//:pkg",
    "pathlib2:dirty": "@examples_checked_in_requirements_bzl__pathlib2_2_3_2_dirty//:pkg",
    "pbr": "@examples_checked_in_requirements_bzl__pbr_4_3_0//:pkg",
    "pbr:dirty": "@examples_checked_in_requirements_bzl__pbr_4_3_0_dirty//:pkg",
    "pip": "@examples_checked_in_requirements_bzl__pip_9_0_0//:pkg",
    "pip:dirty": "@examples_checked_in_requirements_bzl__pip_9_0_0_dirty//:pkg",
    "pluggy": "@examples_checked_in_requirements_bzl__pluggy_0_7_1//:pkg",
    "pluggy:dirty": "@examples_checked_in_requirements_bzl__pluggy_0_7_1_dirty//:pkg",
    "ply": "@examples_checked_in_requirements_bzl__ply_3_8//:pkg",
    "ply:dirty": "@examples_checked_in_requirements_bzl__ply_3_8_dirty//:pkg",
    "proto-google-cloud-datastore-v1": "@examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4//:pkg",
    "proto-google-cloud-datastore-v1:dirty": "@examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4_dirty//:pkg",
    "proto-google-cloud-datastore-v1[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4//:grpc",
    "proto-google-cloud-datastore-v1:dirty[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4_dirty//:grpc",
    "proto-google-cloud-error-reporting-v1beta1": "@examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3//:pkg",
    "proto-google-cloud-error-reporting-v1beta1:dirty": "@examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3_dirty//:pkg",
    "proto-google-cloud-error-reporting-v1beta1[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3//:grpc",
    "proto-google-cloud-error-reporting-v1beta1:dirty[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3_dirty//:grpc",
    "proto-google-cloud-logging-v2": "@examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3//:pkg",
    "proto-google-cloud-logging-v2:dirty": "@examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3_dirty//:pkg",
    "proto-google-cloud-logging-v2[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3//:grpc",
    "proto-google-cloud-logging-v2:dirty[grpc]": "@examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3_dirty//:grpc",
    "protobuf": "@examples_checked_in_requirements_bzl__protobuf_3_6_1//:pkg",
    "protobuf:dirty": "@examples_checked_in_requirements_bzl__protobuf_3_6_1_dirty//:pkg",
    "psutil": "@examples_checked_in_requirements_bzl__psutil_5_4_7//:pkg",
    "psutil:dirty": "@examples_checked_in_requirements_bzl__psutil_5_4_7_dirty//:pkg",
    "psutil[enum]": "@examples_checked_in_requirements_bzl__psutil_5_4_7//:enum",
    "psutil:dirty[enum]": "@examples_checked_in_requirements_bzl__psutil_5_4_7_dirty//:enum",
    "py": "@examples_checked_in_requirements_bzl__py_1_6_0//:pkg",
    "py:dirty": "@examples_checked_in_requirements_bzl__py_1_6_0_dirty//:pkg",
    "pyasn1": "@examples_checked_in_requirements_bzl__pyasn1_0_4_4//:pkg",
    "pyasn1:dirty": "@examples_checked_in_requirements_bzl__pyasn1_0_4_4_dirty//:pkg",
    "pyasn1-modules": "@examples_checked_in_requirements_bzl__pyasn1_modules_0_2_2//:pkg",
    "pyasn1-modules:dirty": "@examples_checked_in_requirements_bzl__pyasn1_modules_0_2_2_dirty//:pkg",
    "pytest": "@examples_checked_in_requirements_bzl__pytest_3_8_2//:pkg",
    "pytest:dirty": "@examples_checked_in_requirements_bzl__pytest_3_8_2_dirty//:pkg",
    "pytest-mock": "@examples_checked_in_requirements_bzl__pytest_mock_1_6_2//:pkg",
    "pytest-mock:dirty": "@examples_checked_in_requirements_bzl__pytest_mock_1_6_2_dirty//:pkg",
    "python-dateutil": "@examples_checked_in_requirements_bzl__python_dateutil_2_7_3//:pkg",
    "python-dateutil:dirty": "@examples_checked_in_requirements_bzl__python_dateutil_2_7_3_dirty//:pkg",
    "pytz": "@examples_checked_in_requirements_bzl__pytz_2018_5//:pkg",
    "pytz:dirty": "@examples_checked_in_requirements_bzl__pytz_2018_5_dirty//:pkg",
    "pyyaml": "@examples_checked_in_requirements_bzl__PyYAML_3_13//:pkg",
    "pyyaml:dirty": "@examples_checked_in_requirements_bzl__PyYAML_3_13_dirty//:pkg",
    "requests": "@examples_checked_in_requirements_bzl__requests_2_19_1//:pkg",
    "requests:dirty": "@examples_checked_in_requirements_bzl__requests_2_19_1_dirty//:pkg",
    "rsa": "@examples_checked_in_requirements_bzl__rsa_4_0//:pkg",
    "rsa:dirty": "@examples_checked_in_requirements_bzl__rsa_4_0_dirty//:pkg",
    "scandir": "@examples_checked_in_requirements_bzl__scandir_1_9_0//:pkg",
    "scandir:dirty": "@examples_checked_in_requirements_bzl__scandir_1_9_0_dirty//:pkg",
    "scikit-learn": "@examples_checked_in_requirements_bzl__scikit_learn_0_17_1//:pkg",
    "scikit-learn:dirty": "@examples_checked_in_requirements_bzl__scikit_learn_0_17_1_dirty//:pkg",
    "scipy": "@examples_checked_in_requirements_bzl__scipy_0_17_1//:pkg",
    "scipy:dirty": "@examples_checked_in_requirements_bzl__scipy_0_17_1_dirty//:pkg",
    "setuptools": "@examples_checked_in_requirements_bzl__setuptools_40_4_3//:pkg",
    "setuptools:dirty": "@examples_checked_in_requirements_bzl__setuptools_40_4_3_dirty//:pkg",
    "setuptools[certs]": "@examples_checked_in_requirements_bzl__setuptools_40_4_3//:certs",
    "setuptools:dirty[certs]": "@examples_checked_in_requirements_bzl__setuptools_40_4_3_dirty//:certs",
    "setuptools[ssl]": "@examples_checked_in_requirements_bzl__setuptools_40_4_3//:ssl",
    "setuptools:dirty[ssl]": "@examples_checked_in_requirements_bzl__setuptools_40_4_3_dirty//:ssl",
    "setuptools-scm": "@examples_checked_in_requirements_bzl__setuptools_scm_2_0_0//:pkg",
    "setuptools-scm:dirty": "@examples_checked_in_requirements_bzl__setuptools_scm_2_0_0_dirty//:pkg",
    "six": "@examples_checked_in_requirements_bzl__six_1_11_0//:pkg",
    "six:dirty": "@examples_checked_in_requirements_bzl__six_1_11_0_dirty//:pkg",
    "urllib3": "@examples_checked_in_requirements_bzl__urllib3_1_23//:pkg",
    "urllib3:dirty": "@examples_checked_in_requirements_bzl__urllib3_1_23_dirty//:pkg",
}

all_requirements = _requirements.values()
requirements_map = _requirements

def requirement_repo(name):
    return requirement(name).split(":")[0]

def requirement(name, binary = None):
    key = name.lower()
    if key not in _requirements:
        fail("Could not find pip-provided dependency: '%s'" % name)
    if binary:
        return _requirements[key].split(":")[0] + ":entrypoint_" + binary
    return _requirements[key]

def pip_install():
    all_libs = {
        "atomicwrites": {
            "name": "examples_checked_in_requirements_bzl__atomicwrites_1_2_1",
            "version": "1.2.1",
            "wheel_name": "atomicwrites-1.2.1-py2.py3-none-any.whl",
            "sha256": "b5590abbfdbec2410c84752e19d0227a81354fbeaa5d0372d08953ec6b313864",
        },
        "attrs": {
            "name": "examples_checked_in_requirements_bzl__attrs_18_2_0",
            "version": "18.2.0",
            "wheel_name": "attrs-18.2.0-py2.py3-none-any.whl",
            "sha256": "f98edf07e67082453faec9f59492b4162b04a475c6eeafb8c8f26bd934913241",
        },
        "backports.functools-lru-cache": {
            "name": "examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5",
            "version": "1.5",
            "wheel_name": "backports.functools_lru_cache-1.5-py2.py3-none-any.whl",
            "sha256": "1cccca3b6013e367a02d3340892ccbb504b12595782633efde9fac0db770cfad",
        },
        "backports.ssl-match-hostname": {
            "name": "examples_checked_in_requirements_bzl__backports_ssl_match_hostname_3_5_0_1",
            "version": "3.5.0.1",
            "wheel_name": "backports.ssl_match_hostname-3.5.0.1-py2-none-any.whl",
            "sha256": "f0775ebe361e42194dc655e9df739fd0501a379153882bdef7011c3c92c7fc9f",
        },
        "botocore": {
            "name": "examples_checked_in_requirements_bzl__botocore_1_12_18",
            "version": "1.12.18",
            "wheel_name": "botocore-1.12.18-py2.py3-none-any.whl",
            "sha256": "d557fa8c0cca2e23965c1967977ba06a483ade86e8d7ccd616acff08e94d822e",
            "transitive_runtime_deps": ["docutils", "jmespath", "python-dateutil", "six", "urllib3"],
        },
        "cachetools": {
            "name": "examples_checked_in_requirements_bzl__cachetools_2_1_0",
            "version": "2.1.0",
            "wheel_name": "cachetools-2.1.0-py2.py3-none-any.whl",
            "sha256": "56203d51f0b535b80a63303f5c7bf87d58d209d8fadaaf2c1667d53682fc7996",
        },
        "certifi": {
            "name": "examples_checked_in_requirements_bzl__certifi_2018_8_24",
            "version": "2018.8.24",
            "wheel_name": "certifi-2018.8.24-py2.py3-none-any.whl",
            "sha256": "8b7c2cd0afac519694d76bebb12d3cbb2922c66a153c470ce3ac3bafaf971649",
        },
        "chardet": {
            "name": "examples_checked_in_requirements_bzl__chardet_3_0_4",
            "version": "3.0.4",
            "wheel_name": "chardet-3.0.4-py2.py3-none-any.whl",
            "sha256": "eceb73485c78be26871d452227318d07ef2f279ff1b0397c8b18a0fb178b6e6d",
        },
        "dill": {
            "name": "examples_checked_in_requirements_bzl__dill_0_2_8_2",
            "version": "0.2.8.2",
            "wheel_name": "dill-0.2.8.2-py2-none-any.whl",
            "sha256": "40c9b64f067fa1795065b5c13f7d52db6c7e19a77fd619fbef078adcad2d1426",
        },
        "docutils": {
            "name": "examples_checked_in_requirements_bzl__docutils_0_14",
            "version": "0.14",
            "wheel_name": "docutils-0.14-py2-none-any.whl",
            "sha256": "e2d3ea889f39dd89360bcefa9afa36694b9c396e207eb2efd2cc86fae8409e5b",
        },
        "enum34": {
            "name": "examples_checked_in_requirements_bzl__enum34_1_1_6",
            "version": "1.1.6",
            "wheel_name": "enum34-1.1.6-py2-none-any.whl",
            "sha256": "9e683da1e8212522cd5d322080b9a6ad11ae816c1fc4c0dd907af52f4cbfae92",
        },
        "funcsigs": {
            "name": "examples_checked_in_requirements_bzl__funcsigs_1_0_2",
            "version": "1.0.2",
            "wheel_name": "funcsigs-1.0.2-py2.py3-none-any.whl",
            "sha256": "46f59d0ea3ffa5aab8c75782fbb46350c091f4ced82b8c06c32db25bd9349918",
        },
        "future": {
            "name": "examples_checked_in_requirements_bzl__future_0_16_0",
            "version": "0.16.0",
            "wheel_name": "future-0.16.0-py2-none-any.whl",
            "sha256": "ee46a3ebc86057dbacf9036c28857860f3195eeff45315aae175ffc60670d9f6",
        },
        "futures": {
            "name": "examples_checked_in_requirements_bzl__futures_3_2_0",
            "version": "3.2.0",
            "wheel_name": "futures-3.2.0-py2-none-any.whl",
            "sha256": "3bfcbf06937bfa6ae07b1edb114ab0dc365ed2f8f07444db7f3742e33d9d46c7",
        },
        "gapic-google-cloud-datastore-v1": {
            "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_datastore_v1_0_15_3",
            "version": "0.15.3",
            "wheel_name": "gapic_google_cloud_datastore_v1-0.15.3-py2-none-any.whl",
            "sha256": "ef00f2cd34d6480f259520d99d2d636dc89c980d4dec46cae8d781f7c55ea617",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "gapic-google-cloud-error-reporting-v1beta1": {
            "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_error_reporting_v1beta1_0_15_3",
            "version": "0.15.3",
            "wheel_name": "gapic_google_cloud_error_reporting_v1beta1-0.15.3-py2-none-any.whl",
            "sha256": "9cc8e4099c8b323ccf0f397439e5636c129d769acf9550b9b1c5d11ce12b64cd",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-error-reporting-v1beta1", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "gapic-google-cloud-logging-v2": {
            "name": "examples_checked_in_requirements_bzl__gapic_google_cloud_logging_v2_0_91_3",
            "version": "0.91.3",
            "wheel_name": "gapic_google_cloud_logging_v2-0.91.3-py2-none-any.whl",
            "sha256": "9f69f0b5b980f430f02c3a194e322e9bb29e2cfda5661ef94efaccdf59e949db",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-api-core": {
            "name": "examples_checked_in_requirements_bzl__google_api_core_0_1_4",
            "version": "0.1.4",
            "wheel_name": "google_api_core-0.1.4-py2.py3-none-any.whl",
            "sha256": "dffdb9e076a49e479f6e56e437ebc296e1aa774278c53a914dcaf0f7ccdbb37c",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-auth", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-auth": {
            "name": "examples_checked_in_requirements_bzl__google_auth_1_5_1",
            "version": "1.5.1",
            "wheel_name": "google_auth-1.5.1-py2.py3-none-any.whl",
            "sha256": "1f05bca0335bf1b359b4adf0057ce715a5a08fc62ba4885c7d1f337c1aac734b",
            "transitive_runtime_deps": ["cachetools", "pyasn1", "pyasn1-modules", "rsa", "six"],
        },
        "google-cloud": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_0_29_0",
            "version": "0.29.0",
            "wheel_name": "google_cloud-0.29.0-py2.py3-none-any.whl",
            "sha256": "201609878669bd7786665ad7b5b5af84bb08a0309f7ab9977c0993ffcd6175f2",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-datastore-v1", "gapic-google-cloud-error-reporting-v1beta1", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-bigquery", "google-cloud-bigtable", "google-cloud-core", "google-cloud-datastore", "google-cloud-dns", "google-cloud-error-reporting", "google-cloud-firestore", "google-cloud-language", "google-cloud-logging", "google-cloud-monitoring", "google-cloud-pubsub", "google-cloud-resource-manager", "google-cloud-runtimeconfig", "google-cloud-spanner", "google-cloud-speech", "google-cloud-storage", "google-cloud-trace", "google-cloud-translate", "google-cloud-videointelligence", "google-cloud-vision", "google-gax", "google-resumable-media", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "proto-google-cloud-error-reporting-v1beta1", "proto-google-cloud-logging-v2", "protobuf", "psutil", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-bigquery": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_bigquery_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_bigquery-0.28.0-py2.py3-none-any.whl",
            "sha256": "8d8ee871c097af8daad63772485f01f2b370b95722eba3495d933adfb87fffea",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-resumable-media", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-bigtable": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_bigtable_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_bigtable-0.28.1-py2.py3-none-any.whl",
            "sha256": "d5cc9754ff351addd47a98ed75efdd338146223a3d25ff3c47df13f54046ee27",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-core": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_core_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_core-0.28.1-py2.py3-none-any.whl",
            "sha256": "cad5288f6b3faf7411b556a325d629305ee3e7f84b9f162bf9bd5a14cc627280",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-datastore": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_datastore_1_4_0",
            "version": "1.4.0",
            "wheel_name": "google_cloud_datastore-1.4.0-py2.py3-none-any.whl",
            "sha256": "72cf83e7d5cc9ed5b65c2e747ee4b76428ad15192e88274dda0b716fd5a7d3ed",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-datastore-v1", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-datastore-v1", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-dns": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_dns_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_dns-0.28.0-py2.py3-none-any.whl",
            "sha256": "4f6334c6a3b8d22bc147a40c57cfbaad1fb36d5b66610f4c7f581be8b68a6a84",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-error-reporting": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_error_reporting_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_error_reporting-0.28.0-py2.py3-none-any.whl",
            "sha256": "052a4969db60c3adb0735e4d736f3627804d7e22b5ca658b8902cd895cd1db3f",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-error-reporting-v1beta1", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-core", "google-cloud-logging", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-error-reporting-v1beta1", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-firestore": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_firestore_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_firestore-0.28.0-py2.py3-none-any.whl",
            "sha256": "487a330cdd12e7e026ce75500463f54840155ae347555fe00a8ce4e4dd3fc218",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-language": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_language_0_31_0",
            "version": "0.31.0",
            "wheel_name": "google_cloud_language-0.31.0-py2.py3-none-any.whl",
            "sha256": "838e0a463947ba1a3574fa5e81a1e0d1accd0909663a8ce5b85e8b64cab0c2a9",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "enum34", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "grpcio", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-logging": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_logging_1_4_0",
            "version": "1.4.0",
            "wheel_name": "google_cloud_logging-1.4.0-py2.py3-none-any.whl",
            "sha256": "936d235577b34bf81ad0f5be8a0bb1cd0a8833b180bd0e6021fa6eee8d2bdaa3",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "gapic-google-cloud-logging-v2", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "httplib2", "idna", "oauth2client", "ply", "proto-google-cloud-logging-v2", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-monitoring": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_monitoring_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_monitoring-0.28.1-py2.py3-none-any.whl",
            "sha256": "e9f9514d825042af569a963fca0c3257d7ad7e4eeeadd0fa3aadd9081f986411",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-pubsub": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_pubsub_0_29_4",
            "version": "0.29.4",
            "wheel_name": "google_cloud_pubsub-0.29.4-py2.py3-none-any.whl",
            "sha256": "f29bfd183d412ed13bb9ebd7a4180c5e6421121520f2c5f5ac87dd203a98f9da",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "enum34", "futures", "google-api-core", "google-auth", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "idna", "protobuf", "psutil", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-resource-manager": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_resource_manager_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_resource_manager-0.28.1-py2.py3-none-any.whl",
            "sha256": "bb582d9fae6436d2a183ad7b377c573a29c5a8dec13b4c3711105f80dba9fc8b",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-runtimeconfig": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_runtimeconfig_0_28_1",
            "version": "0.28.1",
            "wheel_name": "google_cloud_runtimeconfig-0.28.1-py2.py3-none-any.whl",
            "sha256": "a97939706d93299a424e05de5ae9f526cd3b6bd926bee6b946da2fbd5ad535be",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-spanner": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_spanner_0_29_0",
            "version": "0.29.0",
            "wheel_name": "google_cloud_spanner-0.29.0-py2.py3-none-any.whl",
            "sha256": "3210d78f277ecf4d076f2b337f7822b6287a4787682ce6b16ace5c2de9b313d2",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpc-google-iam-v1", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-speech": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_speech_0_30_0",
            "version": "0.30.0",
            "wheel_name": "google_cloud_speech-0.30.0-py2.py3-none-any.whl",
            "sha256": "bbd2f94028b571faad1afa74dc0ee7af3d0bf6f234850f56d93919006c8bfc4a",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-storage": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_storage_1_6_0",
            "version": "1.6.0",
            "wheel_name": "google_cloud_storage-1.6.0-py2.py3-none-any.whl",
            "sha256": "89ffe0fa4f8583a3808a9784b682c62ed01b752292ace47d86becbbc3e1e9b6b",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-resumable-media", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-trace": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_trace_0_16_0",
            "version": "0.16.0",
            "wheel_name": "google_cloud_trace-0.16.0-py2-none-any.whl",
            "sha256": "b90cc251ea9cf08ff404bcc9489df0fa0e41d69ada3dd4bd10fd557f545916c7",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-translate": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_translate_1_3_1",
            "version": "1.3.1",
            "wheel_name": "google_cloud_translate-1.3.1-py2.py3-none-any.whl",
            "sha256": "c605813b8a48826baf401b4e94717d62976361ad35e6e94401330a1b9aabb1a9",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "futures", "google-api-core", "google-auth", "google-cloud-core", "googleapis-common-protos", "idna", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-videointelligence": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_videointelligence_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_videointelligence-0.28.0-py2.py3-none-any.whl",
            "sha256": "614037ac8199a831aa1b897d052caaaaf42ddeb2fceecc5ad8fc23a33396f24a",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-cloud-vision": {
            "name": "examples_checked_in_requirements_bzl__google_cloud_vision_0_28_0",
            "version": "0.28.0",
            "wheel_name": "google_cloud_vision-0.28.0-py2.py3-none-any.whl",
            "sha256": "49931a24ba7e1f075dc5e149e6b910488869dfc9ead3546b7acb7f22cb7e90f1",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-api-core", "google-auth", "google-cloud-core", "google-gax", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pytz", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-gax": {
            "name": "examples_checked_in_requirements_bzl__google_gax_0_15_16",
            "version": "0.15.16",
            "wheel_name": "google_gax-0.15.16-py2.py3-none-any.whl",
            "sha256": "0bf309e4bbef025415f57cb45885a72374dc23bb2e2a6759397135fafeca3fec",
            "transitive_runtime_deps": ["cachetools", "certifi", "chardet", "dill", "enum34", "future", "futures", "google-auth", "googleapis-common-protos", "grpcio", "idna", "ply", "protobuf", "pyasn1", "pyasn1-modules", "requests", "rsa", "setuptools", "six", "urllib3"],
        },
        "google-resumable-media": {
            "name": "examples_checked_in_requirements_bzl__google_resumable_media_0_3_1",
            "version": "0.3.1",
            "wheel_name": "google_resumable_media-0.3.1-py2.py3-none-any.whl",
            "sha256": "b17562db945f68b6c1db0d23ab06d46d0c086b807e12438226f80f41bdbea130",
            "extras": ["requests"],
            "transitive_runtime_deps": ["six"],
        },
        "googleapis-common-protos": {
            "name": "examples_checked_in_requirements_bzl__googleapis_common_protos_1_5_3",
            "version": "1.5.3",
            "wheel_name": "googleapis_common_protos-1.5.3-py2-none-any.whl",
            "sha256": "4d11621d307644795128f106ed18ca232a540f5d83f1160f33223b7ecaff7f8c",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["protobuf", "setuptools", "six"],
        },
        "grpc-google-iam-v1": {
            "name": "examples_checked_in_requirements_bzl__grpc_google_iam_v1_0_11_4",
            "version": "0.11.4",
            "wheel_name": "grpc_google_iam_v1-0.11.4-py2-none-any.whl",
            "sha256": "a8d7364019651ee747f98d8abe108964909812aba6d8bef55f849fd1b0ea4270",
            "transitive_runtime_deps": ["enum34", "futures", "googleapis-common-protos", "grpcio", "protobuf", "setuptools", "six"],
        },
        "grpcio": {
            "name": "examples_checked_in_requirements_bzl__grpcio_1_15_0",
            "version": "1.15.0",
            "wheel_name": "grpcio-1.15.0-cp27-cp27mu-manylinux1_x86_64.whl",
            "sha256": "88de9b2dc62e4b952818b900cd640e41a33ebdf5ca2ac15bef19efc62169697c",
            "transitive_runtime_deps": ["enum34", "futures", "six"],
        },
        "h5py": {
            "name": "examples_checked_in_requirements_bzl__h5py_2_8_0",
            "version": "2.8.0",
            "wheel_name": "h5py-2.8.0-cp27-cp27mu-manylinux1_x86_64.whl",
            "sha256": "2420138497d8155dbafed4e2e4366cdf62d7acbcd4c3d1ff8dca90d8a5cbf2a3",
            "transitive_runtime_deps": ["numpy", "six"],
        },
        "httplib2": {
            "name": "examples_checked_in_requirements_bzl__httplib2_0_11_3",
            "version": "0.11.3",
            "wheel_name": "httplib2-0.11.3-py2-none-any.whl",
            "sha256": "09f2c6061f8a6a13d48e2c72369fa11458da397a72fb8b854a5b12a76a8b63de",
        },
        "idna": {
            "name": "examples_checked_in_requirements_bzl__idna_2_7",
            "version": "2.7",
            "wheel_name": "idna-2.7-py2.py3-none-any.whl",
            "sha256": "7a49f44f706d4f731921ba7b628cf40d34757958bfed6cf1e98e14b1b84991cd",
        },
        "jmespath": {
            "name": "examples_checked_in_requirements_bzl__jmespath_0_9_3",
            "version": "0.9.3",
            "wheel_name": "jmespath-0.9.3-py2.py3-none-any.whl",
            "sha256": "66ef33e7c4cdfdd0810fa8e29ed905189c65f763712ccb656309961eec6d3e65",
        },
        "keras": {
            "name": "examples_checked_in_requirements_bzl__Keras_2_2_2",
            "version": "2.2.2",
            "wheel_name": "Keras-2.2.2-py2.py3-none-any.whl",
            "sha256": "c49be0b26b68ed95003b8cb6b8ded609872a74fa9b8923eaf9b8e977d8a79c81",
            "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
        },
        "keras-applications": {
            "name": "examples_checked_in_requirements_bzl__Keras_Applications_1_0_4",
            "version": "1.0.4",
            "wheel_name": "Keras_Applications-1.0.4-py2.py3-none-any.whl",
            "sha256": "63ae30c76d22bcb4addba1bdef776dcf020ca01f022e0d557d33cd8ede840bdc",
            "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
        },
        "keras-preprocessing": {
            "name": "examples_checked_in_requirements_bzl__Keras_Preprocessing_1_0_2",
            "version": "1.0.2",
            "wheel_name": "Keras_Preprocessing-1.0.2-py2.py3-none-any.whl",
            "sha256": "7e9e0e0647ad28070ce62fa3b60394e441e34478a1b37986876c3c08983f4f8b",
            "transitive_runtime_deps": ["h5py", "keras", "keras-applications", "keras-preprocessing", "numpy", "pyyaml", "scipy", "six"],
        },
        "mock": {
            "name": "examples_checked_in_requirements_bzl__mock_2_0_0",
            "version": "2.0.0",
            "wheel_name": "mock-2.0.0-py2.py3-none-any.whl",
            "sha256": "791b55ed33eaaa0ffc77040aa1b3df67c969beeefcbd6de5aa532db87086ac3b",
            "transitive_runtime_deps": ["funcsigs", "pbr", "six"],
        },
        "more-itertools": {
            "name": "examples_checked_in_requirements_bzl__more_itertools_4_3_0",
            "version": "4.3.0",
            "wheel_name": "more_itertools-4.3.0-py2-none-any.whl",
            "sha256": "6a01575f029b6733144e37682200a315b3dad2b3700d4c948bc9968d4eb5c378",
            "transitive_runtime_deps": ["six"],
        },
        "numpy": {
            "name": "examples_checked_in_requirements_bzl__numpy_1_14_0",
            "version": "1.14.0",
            "wheel_name": "numpy-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl",
            "sha256": "221c65dcee9eae15f7ee6af804f0de98c4f56c2e397191a6e9abff578f109d74",
        },
        "oauth2client": {
            "name": "examples_checked_in_requirements_bzl__oauth2client_3_0_0",
            "version": "3.0.0",
            "wheel_name": "oauth2client-3.0.0-py2-none-any.whl",
            "sha256": "8c4814d1b3e51e8ec19b111300555f197c9d16fa6c7b19f25e97bfa21b3f963e",
            "transitive_runtime_deps": ["httplib2", "pyasn1", "pyasn1-modules", "rsa", "six"],
        },
        "pathlib2": {
            "name": "examples_checked_in_requirements_bzl__pathlib2_2_3_2",
            "version": "2.3.2",
            "wheel_name": "pathlib2-2.3.2-py2.py3-none-any.whl",
            "sha256": "4a8ab8f429050b78c36aa07f6afef80b6fd8b7074aed7dc4d002c4a32f0287a9",
            "transitive_runtime_deps": ["scandir", "six"],
        },
        "pbr": {
            "name": "examples_checked_in_requirements_bzl__pbr_4_3_0",
            "version": "4.3.0",
            "wheel_name": "pbr-4.3.0-py2.py3-none-any.whl",
            "sha256": "1fab4fd4fcff2a09363c53ff5e1e8358c30265f3d10f57607fa2d5d5596a1ad3",
        },
        "pip": {
            "name": "examples_checked_in_requirements_bzl__pip_9_0_0",
            "version": "9.0.0",
            "wheel_name": "pip-9.0.0-py2.py3-none-any.whl",
            "sha256": "03e46fca65cd6a3c330c14de4776a21895732dfd6050163ece7248ab95f20aa2",
        },
        "pluggy": {
            "name": "examples_checked_in_requirements_bzl__pluggy_0_7_1",
            "version": "0.7.1",
            "wheel_name": "pluggy-0.7.1-py2.py3-none-any.whl",
            "sha256": "1135b8c871f32cb760fc0d26fa41b533d5ca28ee7a736cb834fcfab53d3acb3e",
        },
        "ply": {
            "name": "examples_checked_in_requirements_bzl__ply_3_8",
            "version": "3.8",
            "wheel_name": "ply-3.8-py2.py3-none-any.whl",
            "sha256": "526a96c0e46ff7ce5e054ac9ed8af4ebcd1492ae7aa025e36ba6205c457b48f6",
        },
        "proto-google-cloud-datastore-v1": {
            "name": "examples_checked_in_requirements_bzl__proto_google_cloud_datastore_v1_0_90_4",
            "version": "0.90.4",
            "wheel_name": "proto_google_cloud_datastore_v1-0.90.4-py2-none-any.whl",
            "sha256": "c3b9b8b9425eb4d9614508271b7be25bd5fb8fdf61028ce0aaf7fa0d06eb159d",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
        },
        "proto-google-cloud-error-reporting-v1beta1": {
            "name": "examples_checked_in_requirements_bzl__proto_google_cloud_error_reporting_v1beta1_0_15_3",
            "version": "0.15.3",
            "wheel_name": "proto_google_cloud_error_reporting_v1beta1-0.15.3-py2-none-any.whl",
            "sha256": "ed665caa2790b670e68be490924436a9cf766d02b652d430ca0b3e65eba41d06",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
        },
        "proto-google-cloud-logging-v2": {
            "name": "examples_checked_in_requirements_bzl__proto_google_cloud_logging_v2_0_91_3",
            "version": "0.91.3",
            "wheel_name": "proto_google_cloud_logging_v2-0.91.3-py2-none-any.whl",
            "sha256": "6d2fefd7e61465faabe72aecf8dfeb2d663ee910476104ac5e36a27db67e3614",
            "extras": ["grpc"],
            "transitive_runtime_deps": ["googleapis-common-protos", "httplib2", "oauth2client", "protobuf", "pyasn1", "pyasn1-modules", "rsa", "setuptools", "six"],
        },
        "protobuf": {
            "name": "examples_checked_in_requirements_bzl__protobuf_3_6_1",
            "version": "3.6.1",
            "wheel_name": "protobuf-3.6.1-cp27-cp27mu-manylinux1_x86_64.whl",
            "sha256": "837fca0967503f78ed4f8b2f6053a0377071505b2f36b3318eca542e74d5dae1",
            "transitive_runtime_deps": ["setuptools", "six"],
        },
        "psutil": {
            "name": "examples_checked_in_requirements_bzl__psutil_5_4_7",
            "version": "5.4.7",
            "wheel_name": "psutil-5.4.7-cp27-cp27mu-linux_x86_64.whl",
            "sha256": "4f98da243784e6aa04f072dab4fe43f1e452e621bdfe3c40937fef8746117919",
            "extras": ["enum"],
        },
        "py": {
            "name": "examples_checked_in_requirements_bzl__py_1_6_0",
            "version": "1.6.0",
            "wheel_name": "py-1.6.0-py2.py3-none-any.whl",
            "sha256": "9453c2177f8df163c4b7dee47585b496721e49db61ec625a64e868473499c459",
        },
        "pyasn1": {
            "name": "examples_checked_in_requirements_bzl__pyasn1_0_4_4",
            "version": "0.4.4",
            "wheel_name": "pyasn1-0.4.4-py2.py3-none-any.whl",
            "sha256": "837fe76b91c1c7cdeb2f4082bbfabca38ab58f1738812f37669407c96ad54b71",
        },
        "pyasn1-modules": {
            "name": "examples_checked_in_requirements_bzl__pyasn1_modules_0_2_2",
            "version": "0.2.2",
            "wheel_name": "pyasn1_modules-0.2.2-py2.py3-none-any.whl",
            "sha256": "899305df47716c9102a751fd7c00f55943cd861f5ea31b009eef92470c2ef321",
            "transitive_runtime_deps": ["pyasn1"],
        },
        "pytest": {
            "name": "examples_checked_in_requirements_bzl__pytest_3_8_2",
            "version": "3.8.2",
            "wheel_name": "pytest-3.8.2-py2.py3-none-any.whl",
            "sha256": "c9b86d8493fc547b99c33d4e1de421f5591a0b0aafdf7963a3301d8a910d4d27",
            "transitive_runtime_deps": ["atomicwrites", "attrs", "funcsigs", "more-itertools", "pathlib2", "pluggy", "py", "scandir", "setuptools", "six"],
        },
        "pytest-mock": {
            "name": "examples_checked_in_requirements_bzl__pytest_mock_1_6_2",
            "version": "1.6.2",
            "wheel_name": "pytest_mock-1.6.2-py2.py3-none-any.whl",
            "sha256": "a53f4093321a78eb48705755b59e19b7f8284a5e1621a883960c6f22813b229d",
            "transitive_runtime_deps": ["atomicwrites", "attrs", "funcsigs", "mock", "more-itertools", "pathlib2", "pbr", "pluggy", "py", "pytest", "scandir", "setuptools", "six"],
        },
        "python-dateutil": {
            "name": "examples_checked_in_requirements_bzl__python_dateutil_2_7_3",
            "version": "2.7.3",
            "wheel_name": "python_dateutil-2.7.3-py2.py3-none-any.whl",
            "sha256": "42f30fd15b57386970337b232020ba7e073c1612511ecfc7e385aeff2b11ec6d",
            "transitive_runtime_deps": ["six"],
        },
        "pytz": {
            "name": "examples_checked_in_requirements_bzl__pytz_2018_5",
            "version": "2018.5",
            "wheel_name": "pytz-2018.5-py2.py3-none-any.whl",
            "sha256": "42f470cf3b8f771da906e2cfe7e38a9aeddf870e9f4eddaaba42a93054650fca",
        },
        "pyyaml": {
            "name": "examples_checked_in_requirements_bzl__PyYAML_3_13",
            "version": "3.13",
            "wheel_name": "PyYAML-3.13-cp27-cp27mu-linux_x86_64.whl",
            "sha256": "79aba8ba8d8abf83e9fcaca344eb3d9b89af3e8c7f8bdd81571f147113147183",
        },
        "requests": {
            "name": "examples_checked_in_requirements_bzl__requests_2_19_1",
            "version": "2.19.1",
            "wheel_name": "requests-2.19.1-py2.py3-none-any.whl",
            "sha256": "a3c440426f218dfa7f800998113bf481e9e22c171af439593f8957ef3dcbd4c0",
            "transitive_runtime_deps": ["certifi", "chardet", "idna", "urllib3"],
        },
        "rsa": {
            "name": "examples_checked_in_requirements_bzl__rsa_4_0",
            "version": "4.0",
            "wheel_name": "rsa-4.0-py2.py3-none-any.whl",
            "sha256": "32780ca968b0c9adaffc12f40a3bbb2006010c2fca583b329212e3664a6fd56b",
            "transitive_runtime_deps": ["pyasn1"],
        },
        "scandir": {
            "name": "examples_checked_in_requirements_bzl__scandir_1_9_0",
            "version": "1.9.0",
            "wheel_name": "scandir-1.9.0-cp27-cp27mu-linux_x86_64.whl",
            "sha256": "b32c692b83b6e418fbf8f1f273ff360fe37b6e5e9772b7416fa889ebcf11b091",
        },
        "scikit-learn": {
            "name": "examples_checked_in_requirements_bzl__scikit_learn_0_17_1",
            "version": "0.17.1",
            "wheel_name": "scikit_learn-0.17.1-cp27-cp27mu-manylinux1_x86_64.whl",
            "sha256": "4011b62c3465bbae5ac12e5b0d10e8c12b6a074643a03a5f0cc67cc0dadae730",
        },
        "scipy": {
            "name": "examples_checked_in_requirements_bzl__scipy_0_17_1",
            "version": "0.17.1",
            "wheel_name": "scipy-0.17.1-cp27-cp27mu-manylinux1_x86_64.whl",
            "sha256": "3c51acfac3c2d8f5a957c5b44ea1f3fa4da127bbfd03edbc0b523936881e5b07",
        },
        "setuptools": {
            "name": "examples_checked_in_requirements_bzl__setuptools_40_4_3",
            "version": "40.4.3",
            "wheel_name": "setuptools-40.4.3-py2.py3-none-any.whl",
            "sha256": "cd62804b331d3ddc8b7bf8efd98d60c5e1435172719c4c8e64e213b03bc1ecbe",
            "extras": ["certs", "ssl"],
        },
        "setuptools-scm": {
            "name": "examples_checked_in_requirements_bzl__setuptools_scm_2_0_0",
            "version": "2.0.0",
            "wheel_name": "setuptools_scm-2.0.0-py2.py3-none-any.whl",
            "sha256": "00e974a7cb1885f07e8b2e134d3dbd9a1111bd5c6e0654c2d1c21d4e90dd05b7",
        },
        "six": {
            "name": "examples_checked_in_requirements_bzl__six_1_11_0",
            "version": "1.11.0",
            "wheel_name": "six-1.11.0-py2.py3-none-any.whl",
            "sha256": "a7447d0943d880062e4de9d233213c48e33acc24fa3cf8cbbc5eb64c018700e8",
        },
        "urllib3": {
            "name": "examples_checked_in_requirements_bzl__urllib3_1_23",
            "version": "1.23",
            "wheel_name": "urllib3-1.23-py2.py3-none-any.whl",
            "sha256": "08a681628b032b0994d734a19a0900e16bcaeae1b947ddb0d1e23b4e56ff4c40",
        },
    }

    for key, attributes in all_libs.items():
        whl_library(
            key = key,
            all_libs = all_libs,
            python = "@python2//:bin/python",
            **attributes
        )
