workspace(name = "example")

# PIP => bazel transition
git_repository(
    name = "io_bazel_rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "44711d8ef543f6232aec8445fb5adce9a04767f9",
)

load("@io_bazel_rules_python//python:pip.bzl", "pip_repositories", "pip_import")
pip_repositories()

pip_import(
    name="pip_deps",
    requirements="//:requirements-pip.txt"
)
load("@pip_deps//:requirements.bzl", "pip_install")
pip_install()
